-- =====================================================================
-- 043 — DESIGN TEAM · ACCOUNTS, PASSWORDS AND THE DECK LIST
--
--   Generated by db/set-design-passwords.mjs. Do not hand-edit; re-run the
--   script to change a password.
--
--   These are scrypt hashes in the format lib/auth/password.ts verifies —
--   "<saltHex>:<keyHex>". A hash cannot be reversed into the password, so this
--   file is safe to commit. The passwords themselves were typed by whoever ran
--   the script and are recorded nowhere.
--
--   Three things happen here, and nothing else:
--     · the account exists (created if it does not, L3, Interior department);
--     · it signs in with a password, at /deck-login;
--     · it is on ee.concept_deck_editors, which is the list /decks opens for.
--
--   These accounts are NOT given anything on the tracker. Someone who is on
--   both sides is on both lists — that is a row in the tracker's own tables,
--   not something this file decides.
--
--   Idempotent — re-running sets the same hashes and adds nobody twice.
-- =====================================================================

INSERT INTO public.users
  (email, full_name, display_name, access_level, department_id, job_title,
   auth_provider, password_hash)
SELECT v.email, v.name, v.name, 'L3', d.id, 'essentia — design',
       'local', v.hash
  FROM (VALUES
  ('design.vishakha@essentia.in', 'Vishakha', '883dff87ca9bd9a5127de47baf40aedc:10ac6191e0486fd0f45a3cabfc4981a80a1d7fa89c4fa8485ae77e1ad2a9dd940db8a0d7a0bf0da42e25e587fd6ce7e3e94b2e36f994a13e8d62d399131991b7'),
  ('design.akanshamalik@essentia.in', 'Akansha Malik', 'b64b2966e53765b69a41c7fe111f9823:9ce6245a393d0a9ba6c92910380b276c02ac5f4872beefa5cebe6b8b5e464f15e2fc25a287fb39aae3c306ad6aceb7cb5eee514cb5731ba28ab6c2a37cb238db'),
  ('design.ritu@essentia.in', 'Ritu', '913a1cd8252a6b57378238440478e3f1:64ab7221bcb08dde5ed9ec3574d9fe70dd4d418b6c334577beffd468f058458b10366bde3df8b84b14381843457cd16e5fe5750162df9ca62fead58f8eb913a7'),
  ('design.lavika@essentia.in', 'Lavika', '3ee54973562d61f2fd91ed75cc7a16fe:f64e8e5a65f26362ddac5cc19385a270d12df074d1570a819803b05a4ac7d9195a38a6f942a8b6e224524088639c681533f6757c8d980b664d0241f872dc7f50'),
  ('design.jiya@essentia.in', 'Jiya', '1115e66785249c7b8ed692c3bc9b9adc:489e201523b323ce0e9bd7ddddaa6d3b52dba5d6f97e7b71dd9823efdb39a5e242d773c758a8f4ce3925eba31bb6091bec0e8e4aae8c2aab6f5d3e71f9e3a36f')
  ) AS v(email, name, hash)
  LEFT JOIN public.departments d ON d.code = 'INTERIOR'
ON CONFLICT (email) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      auth_provider = 'local',
      is_active = TRUE,
      -- Setting a new password releases the lock. Five wrong tries lock the
      -- account for fifteen minutes (lib/auth/providers/local-password.ts),
      -- and without these two lines a reset left the person still locked out
      -- holding a password that was right -- which reads as "the new one does
      -- not work either" and sends everybody hunting the wrong thing.
      -- change-password.ts has always cleared both; this is the same rule.
      failed_logins = 0,
      locked_until = NULL;

INSERT INTO ee.concept_deck_editors (user_id)
SELECT id FROM public.users WHERE lower(email) IN ('design.vishakha@essentia.in', 'design.akanshamalik@essentia.in', 'design.ritu@essentia.in', 'design.lavika@essentia.in', 'design.jiya@essentia.in')
ON CONFLICT (user_id) DO NOTHING;

DO $$
DECLARE n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n
    FROM public.users u
    JOIN ee.concept_deck_editors e ON e.user_id = u.id
   WHERE u.password_hash IS NOT NULL AND u.auth_provider = 'local'
     AND lower(u.email) IN ('design.vishakha@essentia.in', 'design.akanshamalik@essentia.in', 'design.ritu@essentia.in', 'design.lavika@essentia.in', 'design.jiya@essentia.in');
  IF n <> 5 THEN
    RAISE EXCEPTION 'Expected 5 design accounts with a password on the deck list, found %.', n;
  END IF;
END $$;
