-- =====================================================================
-- 043 — DESIGN TEAM · ACCOUNTS, PASSWORDS AND THE DECK LIST
--
--   Generated by db/set-design-passwords.mjs. Do not hand-edit; re-run the
--   script to change a password.
--
--   These are scrypt hashes in the format lib/auth/password.ts verifies —
--   "<saltHex>:<keyHex>". A hash cannot be reversed into the password, so this
--   file is safe to commit. The passwords themselves were typed by whoever ran
--   the script and are recorded nowhere.
--
--   Three things happen here, and nothing else:
--     · the account exists (created if it does not, L3, Interior department);
--     · it signs in with a password, at /deck-login;
--     · it is on ee.concept_deck_editors, which is the list /decks opens for.
--
--   These accounts are NOT given anything on the tracker. Someone who is on
--   both sides is on both lists — that is a row in the tracker's own tables,
--   not something this file decides.
--
--   Idempotent — re-running sets the same hashes and adds nobody twice.
-- =====================================================================

INSERT INTO public.users
  (email, full_name, display_name, access_level, department_id, job_title,
   auth_provider, password_hash)
SELECT v.email, v.name, v.name, 'L3', d.id, 'essentia — design',
       'local', v.hash
  FROM (VALUES
  ('design.vishakha@essentia.in', 'Vishakha', 'ac4dacf0e245618ef604641f1190070d:ef2393ea8d1b5e959df9478cbdb7390d34612cc2137bbd78a5977d987c4f82042fc75b30e875e17ef830176948c870d96accf4ac855314e33fd3da2e62e73ccb'),
  ('design.akanshamalik@essentia.in', 'Akansha Malik', 'dd5563cd0e592e359cc4ab5b2e6fd65c:0880364be7e127890dcc722191cb2ce0f6f8c7fa577ff3c2ebce2d3076c0323c5fc587267af8b523a7e898778534eb19b79647f2d7b3f71d6e6bc999d3af1c5d'),
  ('design.ritu@essentia.in', 'Ritu', '08caaabdc8d80c29957342d5404a915d:eb762b668df44d6ea6fd7df174304a9276ac04422e2805c8535efa6dbb965934c00f368962d6657c2ddf5d3a5e942669041436f264cca821b42dfdd11133a55f'),
  ('design.lavika@essentia.in', 'Lavika', '4722f6b962cd899141d6c8207c8ed579:be3ff1a4d7197a1420afd28e4b89428fab8d527fdf8d772119ec34209f15c7363b0c726ee46fd747ef122fe6e6aa72e916668bdb991ab3e22a687c5f0e259397'),
  ('design.jiya@essentia.in', 'Jiya', 'd68174485c1bd81fb67894268805d0d2:6d9284edd482405ce10f12b3d6ee180169fd091bc6160b400ca79585857bcab2106be5fe5263db90a327e910df4df9d37f97304549aaae99cce9db3d07531cb2')
  ) AS v(email, name, hash)
  LEFT JOIN public.departments d ON d.code = 'INTERIOR'
ON CONFLICT (email) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      auth_provider = 'local',
      is_active = TRUE;

INSERT INTO ee.concept_deck_editors (user_id)
SELECT id FROM public.users WHERE lower(email) IN ('design.vishakha@essentia.in', 'design.akanshamalik@essentia.in', 'design.ritu@essentia.in', 'design.lavika@essentia.in', 'design.jiya@essentia.in')
ON CONFLICT (user_id) DO NOTHING;

DO $$
DECLARE n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n
    FROM public.users u
    JOIN ee.concept_deck_editors e ON e.user_id = u.id
   WHERE u.password_hash IS NOT NULL AND u.auth_provider = 'local'
     AND lower(u.email) IN ('design.vishakha@essentia.in', 'design.akanshamalik@essentia.in', 'design.ritu@essentia.in', 'design.lavika@essentia.in', 'design.jiya@essentia.in');
  IF n <> 5 THEN
    RAISE EXCEPTION 'Expected 5 design accounts with a password on the deck list, found %.', n;
  END IF;
END $$;
