-- =====================================================================
-- 043 — DESIGN TEAM · ACCOUNTS, PASSWORDS AND THE DECK LIST
--
--   Generated by db/set-design-passwords.mjs. Do not hand-edit; re-run the
--   script to change a password.
--
--   These are scrypt hashes in the format lib/auth/password.ts verifies —
--   "<saltHex>:<keyHex>". A hash cannot be reversed into the password, so this
--   file is safe to commit. The passwords themselves were typed by whoever ran
--   the script and are recorded nowhere.
--
--   Three things happen here, and nothing else:
--     · the account exists (created if it does not, L3, Interior department);
--     · it signs in with a password, at /deck-login;
--     · it is on ee.concept_deck_editors, which is the list /decks opens for.
--
--   These accounts are NOT given anything on the tracker. Someone who is on
--   both sides is on both lists — that is a row in the tracker's own tables,
--   not something this file decides.
--
--   Idempotent — re-running sets the same hashes and adds nobody twice.
-- =====================================================================

INSERT INTO public.users
  (email, full_name, display_name, access_level, department_id, job_title,
   auth_provider, password_hash)
SELECT v.email, v.name, v.name, 'L3', d.id, 'essentia — design',
       'local', v.hash
  FROM (VALUES
  ('design.vishakha@essentia.in', 'Vishakha', 'a72a216fa68f144e98cefa2b175bd01e:db0158fa8428ef763b59cc4a771451bda370111a0943e0a102033d7f534ae3e5863f3d129232c8e4231fcc577d69cb76b7238dc9c95cf634711bab4646c34221'),
  ('design.akanshamalik@essentia.in', 'Akansha Malik', 'daa189d03759e15614943817bc388e82:8c9dad1646b4e498c4a7faf983ebc1bc09255ea94600c8a0207f63c1b4c763934b0ccd312c0572eee30c735c8a4c179ef683d2a14b23df3452f8dd431541175e'),
  ('design.ritu@essentia.in', 'Ritu', 'c8cf8e18ca4dd55c9274956ded8ca325:4129e79bbd4c787ac51a8e063f4b4827951c823cfd25182125065faad5665f806e1e284a65f36c71564fe00e1289d68e27fbdddf23978b02da56ffe70f1c2b51'),
  ('design.lavika@essentia.in', 'Lavika', '4d782b3e640e6a09f9c76cc6be7ee1d3:5bfe7a50969e608c1025e70177497be429d1a290980bddd731f842783132a1174072bca7fe5377bc116d8cb18db8fdbfb18cac11db8369a57ce7eff690e23335'),
  ('design.jiya@essentia.in', 'Jiya', 'dbd04e1a1ef3294526970ec70abf161a:bac64bffb276589d9b4ea18e32c07f4e2ca41f054b49c5ce9bf67ede6fe8d4c49c75cff06de81a4daffb8b5ae2e08cc8c47c1a3f226d6295e304652ce524e729')
  ) AS v(email, name, hash)
  LEFT JOIN public.departments d ON d.code = 'INTERIOR'
ON CONFLICT (email) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      auth_provider = 'local',
      is_active = TRUE,
      -- Setting a new password releases the lock. Five wrong tries lock the
      -- account for fifteen minutes (lib/auth/providers/local-password.ts),
      -- and without these two lines a reset left the person still locked out
      -- holding a password that was right -- which reads as "the new one does
      -- not work either" and sends everybody hunting the wrong thing.
      -- change-password.ts has always cleared both; this is the same rule.
      failed_logins = 0,
      locked_until = NULL;

INSERT INTO ee.concept_deck_editors (user_id)
SELECT id FROM public.users WHERE lower(email) IN ('design.vishakha@essentia.in', 'design.akanshamalik@essentia.in', 'design.ritu@essentia.in', 'design.lavika@essentia.in', 'design.jiya@essentia.in')
ON CONFLICT (user_id) DO NOTHING;

DO $$
DECLARE n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n
    FROM public.users u
    JOIN ee.concept_deck_editors e ON e.user_id = u.id
   WHERE u.password_hash IS NOT NULL AND u.auth_provider = 'local'
     AND lower(u.email) IN ('design.vishakha@essentia.in', 'design.akanshamalik@essentia.in', 'design.ritu@essentia.in', 'design.lavika@essentia.in', 'design.jiya@essentia.in');
  IF n <> 5 THEN
    RAISE EXCEPTION 'Expected 5 design accounts with a password on the deck list, found %.', n;
  END IF;
END $$;
