-- =====================================================================
-- 058 — HR TEAM · ACCOUNTS AND PASSWORDS
--
--   Generated by db/set-hr-passwords.mjs. Do not hand-edit; re-run the
--   script to change a password.
--
--   These are scrypt hashes in the format lib/auth/password.ts verifies —
--   "<saltHex>:<keyHex>". A hash cannot be reversed into the password, so
--   this file is safe to commit. The passwords themselves were typed by
--   whoever ran the script and are recorded nowhere.
--
--   Two things happen here, and nothing else:
--     · the account exists (created if it does not), in the HR department;
--     · it signs in with a password, at /hr-login.
--
--   THE DEPARTMENT IS THE WHOLE POINT. db/049 grants hiring to HR BY
--   DEPARTMENT — a department row beating the level's global row — and there
--   is no global L2 or L3 grant, by design (§36: candidate data is never open
--   to the floor). An account created here WITHOUT the HR department signs in
--   perfectly well and then sees the word "Restricted". If somebody reports
--   that, this is the first thing to check.
--
--   Nobody is given anything else. Reaching the WIO tracker, the decks or the
--   factory is a row in those modules' own lists, not something this file
--   decides.
--
--   Idempotent — re-running sets the same hashes and adds nobody twice.
--   An existing account keeps whatever access level it already has: this file
--   does not demote somebody who was elevated in the portal on purpose.
--
--   ROLLBACK: these are real people's accounts. Deactivate rather than
--             delete — UPDATE public.users SET is_active = FALSE WHERE ...
-- =====================================================================

INSERT INTO public.users
  (email, full_name, display_name, access_level, department_id, job_title,
   auth_provider, password_hash)
SELECT v.email, v.name, v.name, v.level::access_level, d.id, v.title,
       'local', v.hash
  FROM (VALUES
  ('hr.nandy@essentia.in', 'Nandy', 'L3', 'essentia — HR', '8d6763b8c9d954f59ef289393cc16148:b2326ded24d5ae38113952e2f9e81586a7e3098822e892695a1fd2d1be3b1cdc0866f92612a69227a4666e97da8de2548aca58679ce5e1c626b32ee926d4ab3d'),
  ('hr.shivani@essentia.in', 'Shivani', 'L3', 'essentia — HR', '88ec8c5a8501946c3cb277d10bc3cd6d:cc1a669d7382627b914b524ce8241915e209097add13cf6623c17c0b3712cf1ec7edbcd762fa9348e74d2df77276845deaf549721e8eb2f5f1f1fb814d4769a6'),
  ('hr.saurabh@essentia.in', 'Saurabh', 'L3', 'essentia — HR', '935b50bb06f62f689d8ff76841da655f:1c7092935b30cc5fa6ecb129957a35e34d48567b1a7c85ef4207811babf61775b8b2105f9120d72f48c025396a8cb6e684deffcc6cf5650136032e37d70fbb43'),
  ('hr.akash@essentia.in', 'Akash', 'L3', 'essentia — HR', '2aa091ddbb8cf9f29beb26d5b48e169e:294985edaeaf14fdf2929fb03dc6a85609bbe80fcbded0adb6f3dc27a8e2d4c93221039c8519db612c93da4d0cbd3829e69bba108c373fccd829a7ba7fd1dc1c')
  ) AS v(email, name, level, title, hash)
  LEFT JOIN public.departments d ON d.code = 'HR'
ON CONFLICT (email) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      auth_provider = 'local',
      is_active     = TRUE,
      -- The department is re-asserted because it is what grants hiring, and
      -- somebody moved out of HR by hand should not be quietly moved back by
      -- a password reset. It is set here only because this file IS the HR
      -- list: being in it is what says they are in HR.
      department_id = EXCLUDED.department_id;

-- Two things must hold, or somebody signs in to the word "Restricted".
DO $guards$
DECLARE
  homeless INTEGER;
  dept     INTEGER;
BEGIN
  SELECT count(*) INTO dept FROM public.departments WHERE code = 'HR';
  IF dept = 0 THEN
    RAISE EXCEPTION 'there is no HR department in the master (db/002)';
  END IF;

  SELECT count(*) INTO homeless
    FROM public.users u
    LEFT JOIN public.departments d ON d.id = u.department_id
   WHERE u.email IN ('hr.nandy@essentia.in', 'hr.shivani@essentia.in', 'hr.saurabh@essentia.in', 'hr.akash@essentia.in')
     AND (d.code IS DISTINCT FROM 'HR');
  IF homeless > 0 THEN
    RAISE EXCEPTION
      'an HR account is not in the HR department — it would see "Restricted" (% such)',
      homeless;
  END IF;
END $guards$;
