-- =====================================================================
-- 058 — HR TEAM · ACCOUNTS AND PASSWORDS
--
--   Generated by db/set-hr-passwords.mjs. Do not hand-edit; re-run the
--   script to change a password.
--
--   These are scrypt hashes in the format lib/auth/password.ts verifies —
--   "<saltHex>:<keyHex>". A hash cannot be reversed into the password, so
--   this file is safe to commit. The passwords themselves were typed by
--   whoever ran the script and are recorded nowhere.
--
--   Two things happen here, and nothing else:
--     · the account exists (created if it does not), in the HR department;
--     · it signs in with a password, at /hr-login.
--
--   THE DEPARTMENT IS THE WHOLE POINT. db/049 grants hiring to HR BY
--   DEPARTMENT — a department row beating the level's global row — and there
--   is no global L2 or L3 grant, by design (§36: candidate data is never open
--   to the floor). An account created here WITHOUT the HR department signs in
--   perfectly well and then sees the word "Restricted". If somebody reports
--   that, this is the first thing to check.
--
--   Nobody is given anything else. Reaching the WIO tracker, the decks or the
--   factory is a row in those modules' own lists, not something this file
--   decides.
--
--   Idempotent — re-running sets the same hashes and adds nobody twice.
--   An existing account keeps whatever access level it already has: this file
--   does not demote somebody who was elevated in the portal on purpose.
--
--   ROLLBACK: these are real people's accounts. Deactivate rather than
--             delete — UPDATE public.users SET is_active = FALSE WHERE ...
-- =====================================================================

INSERT INTO public.users
  (email, full_name, display_name, access_level, department_id, job_title,
   auth_provider, password_hash)
SELECT v.email, v.name, v.name, v.level::access_level, d.id, v.title,
       'local', v.hash
  FROM (VALUES
  ('hr.shivani@essentia.in', 'Shivani', 'L3', 'essentia — HR', '051e2dd24aeb2a15aa1104fb5009cb54:213a1b5a41b4f920f846a1e35e62ac73f95fcd5b9fb0417d8111c41bcdd9bd51fda20ce73fc3dc95f9f832e2472723f75790d8577685319374ad5ef6d0583ec8'),
  ('hr.saurabh@essentia.in', 'Saurabh', 'L3', 'essentia — HR', '99c113807eedc80aafcbd1dba9a25d7b:7d13d4e86a70e2e050710fb603087c323a6cf5d23c89fd31a207cd5a952188022c0c5e0b01ef5e26f373f9d7373d830eda61083e8c73330e42cc4da31022aa6b'),
  ('hr.akash@essentia.in', 'Akash', 'L3', 'essentia — HR', 'ab38ed90031a90e1e445835d61498a88:c2e98e29b3c8ab9f3f86cc3aecf5404cafc0e5973af0223f790ca98da7e09e51cd666d1f6d8eabd05c0a898cd36f1dc7dd5efcc88bf3ce69eb0faa5b50086db5')
  ) AS v(email, name, level, title, hash)
  LEFT JOIN public.departments d ON d.code = 'HR'
ON CONFLICT (email) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      auth_provider = 'local',
      is_active     = TRUE,
      -- The department is re-asserted because it is what grants hiring, and
      -- somebody moved out of HR by hand should not be quietly moved back by
      -- a password reset. It is set here only because this file IS the HR
      -- list: being in it is what says they are in HR.
      department_id = EXCLUDED.department_id;

-- Two things must hold, or somebody signs in to the word "Restricted".
DO $guards$
DECLARE
  homeless INTEGER;
  dept     INTEGER;
BEGIN
  SELECT count(*) INTO dept FROM public.departments WHERE code = 'HR';
  IF dept = 0 THEN
    RAISE EXCEPTION 'there is no HR department in the master (db/002)';
  END IF;

  SELECT count(*) INTO homeless
    FROM public.users u
    LEFT JOIN public.departments d ON d.id = u.department_id
   WHERE u.email IN ('hr.shivani@essentia.in', 'hr.saurabh@essentia.in', 'hr.akash@essentia.in')
     AND (d.code IS DISTINCT FROM 'HR');
  IF homeless > 0 THEN
    RAISE EXCEPTION
      'an HR account is not in the HR department — it would see "Restricted" (% such)',
      homeless;
  END IF;
END $guards$;
