-- =====================================================================
-- 060 — WIO TEAM · A PASSWORD THEY CAN ACTUALLY TYPE
--
--   Generated by db/set-wio-passwords.mjs. Do not hand-edit; re-run the
--   script to change a password.
--
--   These are scrypt hashes in the format lib/auth/password.ts verifies —
--   "<saltHex>:<keyHex>". A hash cannot be reversed into the password, so
--   this file is safe to commit. The passwords themselves were typed by
--   whoever ran the script and are recorded nowhere.
--
--   WHY. db/035 created these six for Microsoft sign-in — 'entra', no
--   password — and Entra validation was never built. So all three doors were
--   shut at once: password sign-in had no hash to check, Microsoft sign-in
--   had no verifier, and Team passwords (lib/auth/team-reset.ts) refuses any
--   account that is not 'local'. The only six people allowed to change the
--   tracker could not reach it.
--
--   ONE THING HAPPENS HERE, AND NOTHING ELSE: how these six prove who they
--   are. Department, access level and every permission row are untouched.
--   Tracker edit is db/030's grant to L2 and L3 in DRAFTING and stays there.
--
--   UPDATE ONLY — never INSERT. If an email here does not exist, that is a
--   typo or a renamed account, and creating a second account for the same
--   person is worse than failing. The guard below raises instead.
--
--   Idempotent. Re-running sets the same hashes.
--
--   WHEN ENTRA LANDS: set auth_provider back to 'entra', clear the hashes,
--   and drop this file from db/lib.mjs DEFAULT_FILES.
--
--   ROLLBACK: UPDATE public.users
--                SET auth_provider = 'entra', password_hash = NULL
--              WHERE lower(email) IN ('dipmallya.wio@essentia.in', 'neeraj.wio@essentia.in', 'wio.vishal@essentia.in', 'wio.anshul@essentia.in', 'wio.atul@essentia.in', 'jyoti.drafting@essentia.in');
-- =====================================================================

UPDATE public.users u
   SET password_hash = v.hash,
       auth_provider = 'local',
       failed_logins = 0,
       locked_until  = NULL,
       is_active     = TRUE,
       updated_at    = NOW()
  FROM (VALUES
  ('dipmallya.wio@essentia.in', '500ad5d3754f9d0f2ad03e53071da32d:bd52ff853349d58ac1a8080ff1043883a6b7f88e6f6eac189389a71bd7c5d68a569c8673b0d7f790c896b9dceb6524e7665bda6de7aafdc55a24aeae7b5c899e'),
  ('neeraj.wio@essentia.in', '36ad7d607e0ba86e6b49fe92073047d1:99c6a332d2fa0aabcf449c63aa943490b2d1b487c2de200d2e1d6317b8bf7a3bd6ba975339179191970afe7e913c45bfef3a734a9abc019a4c54a9bb150fb19d'),
  ('wio.vishal@essentia.in', 'a0c7d69f0541593ab308f60f3146a7e6:89666e270d923634ecc19d2ff9b0fef667b69dc36537504d303d96dfbc67ced57f69b52926e382c805954a7ee5ae42bfc810646143fa76975f20fc1d1f9be9ee'),
  ('wio.anshul@essentia.in', 'ddb71ef0c4862d53912d5e6b7e1b643d:25bbd6fb011dca397c615cd1f6f06b5a0c2a05cff189d9b92c44ec8c816965b5d322c12b84cf18c9976de622e1028f436aad87799d0975f76e451e9ec8b478e6'),
  ('wio.atul@essentia.in', '8b826c57dce5bfcdc964f75ad4c44c64:3e7d492afe967371787d0bef31a002cbef71afdeec81d52b5fc3983d9992afd87fd12c25e11dfce4e95df7ec902d619fece4470ed3b24d6c02c56a8e5fc24226'),
  ('Jyoti.drafting@essentia.in', 'cd51d4c8d366ef15ba75b09048da34ca:28afd564f45f43a1226e213521407e29cf9c4fe892cce19dd84e8a1432b8f3d6c1070180bc1e5754d95970178d5439eee8d44edf4b8400dd84bfa55eb28d05e7')
  ) AS v(email, hash)
 WHERE lower(u.email) = lower(v.email);

-- Three things must hold, or somebody signs in and the tracker is read-only.
DO $guards$
DECLARE
  missing  INTEGER;
  homeless INTEGER;
  unset    INTEGER;
BEGIN
  SELECT 6 - count(*) INTO missing
    FROM public.users
   WHERE lower(email) IN ('dipmallya.wio@essentia.in', 'neeraj.wio@essentia.in', 'wio.vishal@essentia.in', 'wio.anshul@essentia.in', 'wio.atul@essentia.in', 'jyoti.drafting@essentia.in');
  IF missing > 0 THEN
    RAISE EXCEPTION
      'a WIO team email in db/060 has no account (% missing) — check the spelling against db/035',
      missing;
  END IF;

  SELECT count(*) INTO homeless
    FROM public.users u
    LEFT JOIN public.departments d ON d.id = u.department_id
   WHERE lower(u.email) IN ('dipmallya.wio@essentia.in', 'neeraj.wio@essentia.in', 'wio.vishal@essentia.in', 'wio.anshul@essentia.in', 'wio.atul@essentia.in', 'jyoti.drafting@essentia.in')
     AND (d.code IS DISTINCT FROM 'DRAFTING');
  IF homeless > 0 THEN
    RAISE EXCEPTION
      'a WIO account is not in DRAFTING — it would sign in and find the tracker read-only (% such)',
      homeless;
  END IF;

  SELECT count(*) INTO unset
    FROM public.users
   WHERE lower(email) IN ('dipmallya.wio@essentia.in', 'neeraj.wio@essentia.in', 'wio.vishal@essentia.in', 'wio.anshul@essentia.in', 'wio.atul@essentia.in', 'jyoti.drafting@essentia.in')
     AND (password_hash IS NULL OR auth_provider <> 'local');
  IF unset > 0 THEN
    RAISE EXCEPTION
      'a WIO account still cannot sign in after this file ran (% such)',
      unset;
  END IF;
END $guards$;
