/**
 * Schema validation harness.
 *
 * Loads the full schema (and any seed files that exist) into PGlite —
 * embedded PostgreSQL with real semantics, including pgvector — so the SQL
 * is proven to load end-to-end without a local Postgres install.
 * Exit code 0 = everything loaded and smoke checks passed.
 *
 * Usage:  npm run validate            (from db/)
 *         node validate.mjs 001_essentia_schema.sql   (specific files)
 */
import { createDb, loadSqlFiles, resolveFiles } from "./lib.mjs";

const requested = process.argv.slice(2);
const files = resolveFiles(requested);

const db = createDb();
const failedFile = await loadSqlFiles(db, files);
let failed = Boolean(failedFile);

if (!failed) {
  // Smoke checks: document-number generators and the golden-thread trigger.
  const checks = [
    {
      name: "next_project_code format ED/YY-YY/NNN",
      sql: "SELECT next_project_code() AS v",
      ok: (v) => /^ED\/\d{2}-\d{2}\/\d{3}$/.test(v),
    },
    {
      name: "next_wio_number format WIO/YY-YY/NNN/DEPT",
      sql: "SELECT next_wio_number('ARCH') AS v",
      ok: (v) => /^WIO\/\d{2}-\d{2}\/\d{3}\/ARCH$/.test(v),
    },
    {
      name: "next_po_number format ESS/PO/YYYY/####",
      sql: "SELECT next_po_number() AS v",
      ok: (v) => /^ESS\/PO\/\d{4}\/\d{4}$/.test(v),
    },
    {
      name: "project_code auto-generated by trigger",
      sql: `
        WITH fam AS (
          INSERT INTO public.families (primary_contact) VALUES ('Validation Family')
          RETURNING id
        )
        INSERT INTO ee.projects (family_id, site_address)
        SELECT id, 'Validation Site' FROM fam
        RETURNING project_code AS v`,
      ok: (v) => /^ED\/\d{2}-\d{2}\/\d{3}$/.test(v),
    },
    {
      // Two statements: a data-modifying CTE is invisible to reads of the
      // same table later in the same statement (snapshot semantics).
      name: "ee.wio_clock view computes RAG",
      setupSql: `
        INSERT INTO ee.wio (wio_number, project_id, department_code, target_pio_date)
        SELECT next_wio_number('3D'), id, '3D', CURRENT_DATE + 3
        FROM ee.projects LIMIT 1`,
      sql: "SELECT clock_rag AS v FROM ee.wio_clock WHERE department_code = '3D'",
      ok: (v) => v === "amber",
    },
    {
      name: "views are security_invoker (RLS not bypassed through wio_clock)",
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.wio_clock",
      ok: (v) => v === "0",
      asRestrictedRole: true,
    },
    {
      name: "RLS: no user context => zero projects visible",
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "0",
      asRestrictedRole: true,
    },
    {
      name: "factory master: 9 stations = 7 active + 2 reserved",
      sql: `SELECT (COUNT(*) FILTER (WHERE status = 'active'))::TEXT || '/' ||
                   (COUNT(*) FILTER (WHERE status = 'reserved'))::TEXT AS v
            FROM factory.departments`,
      ok: (v) => v === "7/2",
    },
    {
      name: "RBAC: L3 read on billing is denied (§36)",
      sql: `SELECT allowed::TEXT AS v FROM public.permissions
            WHERE access_level = 'L3' AND resource_type = 'billing'
              AND action_code = 'read' AND department_id IS NULL`,
      ok: (v) => v === "false",
    },
    {
      name: "RBAC: L2 approve on wio is allowed, own dept",
      sql: `SELECT (allowed AND scope = 'own_dept')::TEXT AS v FROM public.permissions
            WHERE access_level = 'L2' AND resource_type = 'wio'
              AND action_code = 'approve' AND department_id IS NULL`,
      ok: (v) => v === "true",
    },
    {
      name: "RBAC: L2 approve on pio explicitly denied (§26 chain)",
      sql: `SELECT allowed::TEXT AS v FROM public.permissions
            WHERE access_level = 'L2' AND resource_type = 'pio'
              AND action_code = 'approve' AND department_id IS NULL`,
      ok: (v) => v === "false",
    },
    {
      name: "workflow: pio_approval has the 3-step chain",
      sql: `SELECT COUNT(*)::TEXT AS v FROM portal.workflow_steps
            WHERE workflow_code = 'pio_approval'`,
      ok: (v) => v === "3",
    },
    {
      name: "config: ai.provider resolves to anthropic",
      sql: `SELECT value #>> '{}' AS v FROM portal.app_config WHERE key = 'ai.provider'`,
      ok: (v) => v === "anthropic",
    },
    {
      name: "notifications: template library seeded",
      sql: `SELECT (COUNT(*) >= 10)::TEXT AS v FROM portal.notification_templates`,
      ok: (v) => v === "true",
    },
    // 4 = 3 fixture projects + the unassigned one created by the trigger
    // smoke check above — which only L0/L1 can see (no team membership).
    {
      name: "RLS matrix: L0 founder sees all 4 projects incl. unassigned",
      setupSql: `SELECT set_config('app.user_id', '00000000-0000-4000-8000-000000000002', false),
                        set_config('app.user_access_level', 'L0', false)`,
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "4",
      asRestrictedRole: true,
    },
    {
      name: "RLS matrix: L1 leadership sees all 4 projects incl. unassigned",
      setupSql: `SELECT set_config('app.user_id', '00000000-0000-4000-8000-000000000003', false),
                        set_config('app.user_access_level', 'L1', false)`,
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "4",
      asRestrictedRole: true,
    },
    {
      name: "RLS matrix: L2 TL sees exactly their 3 assigned projects",
      setupSql: `SELECT set_config('app.user_id', '00000000-0000-4000-8000-000000000001', false),
                        set_config('app.user_access_level', 'L2', false)`,
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "3",
      asRestrictedRole: true,
    },
    {
      name: "RLS matrix: unassigned L3 sees zero projects",
      setupSql: `SELECT set_config('app.user_id', '00000000-0000-4000-8000-000000000004', false),
                        set_config('app.user_access_level', 'L3', false)`,
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "0",
      asRestrictedRole: true,
    },
    {
      name: "engine default-deny: L3 has no hr_access grant on users",
      sql: `SELECT COUNT(*)::TEXT AS v FROM public.permissions
            WHERE access_level = 'L3' AND resource_type = 'users'
              AND action_code = 'hr_access' AND allowed`,
      ok: (v) => v === "0",
    },
    {
      name: "audit trail carries actor_role",
      sql: `SELECT COUNT(*)::TEXT AS v FROM information_schema.columns
            WHERE table_schema = 'audit' AND table_name = 'log'
              AND column_name = 'actor_role'`,
      ok: (v) => v === "1",
    },
    {
      name: "auth: portal.sessions table exists",
      sql: `SELECT COUNT(*)::TEXT AS v FROM information_schema.tables
            WHERE table_schema = 'portal' AND table_name = 'sessions'`,
      ok: (v) => v === "1",
    },
    {
      name: "auth: config keys seeded (provider + timeouts)",
      sql: `SELECT COUNT(*)::TEXT AS v FROM portal.app_config
            WHERE key IN ('auth.provider','auth.session_absolute_minutes',
                          'auth.session_idle_minutes','auth.max_concurrent_sessions')`,
      ok: (v) => v === "4",
    },
    {
      name: "auth: dev users carry a scrypt password_hash",
      sql: `SELECT COUNT(*)::TEXT AS v FROM public.users
            WHERE email LIKE 'dev.%@essentia.in' AND password_hash LIKE '%:%'`,
      ok: (v) => v === "4",
    },
    {
      name: "auth: essentia_app can write sessions (grant present)",
      sql: `SELECT has_table_privilege('essentia_app','portal.sessions','INSERT')::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Timeout predicates match validateSession(): a fresh session is
      // neither expired nor idle; an aged one is both flagged correctly.
      name: "auth: session timeout predicates (fresh / idle / expired)",
      setupSql: `
        INSERT INTO portal.sessions (user_id, token_hash, expires_at, last_seen_at) VALUES
          ((SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
           'fresh', NOW() + INTERVAL '8 hours', NOW()),
          ((SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
           'idle',  NOW() + INTERVAL '8 hours', NOW() - INTERVAL '2 hours'),
          ((SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
           'expired', NOW() - INTERVAL '1 minute', NOW())`,
      sql: `SELECT string_agg(token_hash || ':' ||
                     (expires_at <= NOW())::TEXT || '/' ||
                     (last_seen_at < NOW() - INTERVAL '60 minutes')::TEXT, ' ' ORDER BY token_hash) AS v
            FROM portal.sessions WHERE token_hash IN ('fresh','idle','expired')`,
      ok: (v) => v === "expired:true/false fresh:false/false idle:false/true",
    },
    {
      name: "auth: concurrent-cap query keeps newest N sessions",
      setupSql: `
        INSERT INTO portal.sessions (user_id, token_hash, expires_at, created_at)
        SELECT (SELECT id FROM public.users WHERE email='dev.coo@essentia.in'),
               'cap' || g, NOW() + INTERVAL '8 hours', NOW() + (g || ' seconds')::INTERVAL
        FROM generate_series(1,5) g`,
      sql: `WITH keep AS (
              SELECT id FROM portal.sessions
              WHERE user_id = (SELECT id FROM public.users WHERE email='dev.coo@essentia.in')
                AND revoked_at IS NULL
              ORDER BY created_at DESC LIMIT 3)
            SELECT COUNT(*)::TEXT AS v FROM portal.sessions
            WHERE user_id = (SELECT id FROM public.users WHERE email='dev.coo@essentia.in')
              AND revoked_at IS NULL AND id NOT IN (SELECT id FROM keep)`,
      ok: (v) => v === "2",
    },
    {
      name: "keka: portal.sync_runs table exists + grant",
      sql: `SELECT (
              EXISTS(SELECT 1 FROM information_schema.tables
                     WHERE table_schema='portal' AND table_name='sync_runs')
              AND has_table_privilege('essentia_app','portal.sync_runs','INSERT')
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "keka: PIO chain steps carry approver_email seeds",
      sql: `SELECT COUNT(*)::TEXT AS v FROM portal.workflow_steps
            WHERE workflow_code='pio_approval' AND approver_email IS NOT NULL`,
      ok: (v) => v === "3",
    },
    {
      name: "keka: department mapping populated (CRM → CRM_EE)",
      sql: `SELECT value->>'CRM' AS v FROM portal.app_config
            WHERE key='keka.department_mapping'`,
      ok: (v) => v === "CRM_EE",
    },
    {
      // Proves the "arm the approval chain" resolution: a synced approver
      // account links to workflow step 1.
      name: "keka: approver resolution links step 1 to Khushpreet",
      setupSql: `
        INSERT INTO public.users (email, full_name, access_level, is_active, keka_employee_id)
        VALUES ('khushpreet.arora@essentia.in','Khushpreet Arora','L2',TRUE,'K010')
        ON CONFLICT (email) DO NOTHING;
        UPDATE portal.workflow_steps s SET approver_user_id = u.id
        FROM public.users u
        WHERE s.approver_email IS NOT NULL AND lower(u.email)=lower(s.approver_email) AND u.is_active`,
      sql: `SELECT (approver_user_id IS NOT NULL)::TEXT AS v FROM portal.workflow_steps
            WHERE workflow_code='pio_approval' AND step_no=1`,
      ok: (v) => v === "true",
    },
    {
      // Locks in the param-typing fix: the workflow CAS advances a step
      // without the "inconsistent types for $2" failure.
      name: "workflow: CAS advance step 1 → 2 succeeds",
      setupSql: `
        WITH proj AS (SELECT id FROM ee.projects LIMIT 1)
        INSERT INTO portal.workflow_instances (workflow_code, resource_type, resource_id, current_step, status)
        SELECT 'pio_approval', 'pio', id, 1, 'pending' FROM proj;
        UPDATE portal.workflow_instances i
        SET status = 'pending', current_step = 2,
            completed_at = CASE WHEN FALSE::boolean THEN NOW() ELSE NULL END
        WHERE i.workflow_code = 'pio_approval' AND i.status = 'pending' AND i.current_step = 1`,
      sql: `SELECT current_step::TEXT AS v FROM portal.workflow_instances
            WHERE workflow_code = 'pio_approval' ORDER BY started_at DESC LIMIT 1`,
      ok: (v) => v === "2",
    },
    {
      name: "events: routing table seeded (>=10 routes)",
      sql: `SELECT (COUNT(*) >= 10)::TEXT AS v FROM portal.event_routes WHERE is_active`,
      ok: (v) => v === "true",
    },
    {
      name: "events: dedupe_key unique index prevents duplicates",
      setupSql: `INSERT INTO portal.events (event_type, category, dedupe_key)
                 VALUES ('t.dupe','system','DK-1')`,
      sql: `INSERT INTO portal.events (event_type, category, dedupe_key)
            VALUES ('t.dupe','system','DK-1') RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "deliveries: (event,recipient,channel) is unique",
      setupSql: `
        INSERT INTO portal.events (id, event_type, category)
        VALUES ('00000000-0000-4000-8000-0000000000e1','t.deliv','system');
        INSERT INTO portal.notification_deliveries (event_id, recipient_id, channel, notification_type)
        VALUES ('00000000-0000-4000-8000-0000000000e1',
                (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
                'in_app','system_alert')`,
      sql: `INSERT INTO portal.notification_deliveries (event_id, recipient_id, channel, notification_type)
            VALUES ('00000000-0000-4000-8000-0000000000e1',
                    (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
                    'in_app','system_alert') RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "delivery engine: exhausted retries transition to dead-letter",
      setupSql: `
        INSERT INTO portal.events (id, event_type, category)
        VALUES ('00000000-0000-4000-8000-0000000000e2','t.dead','system');
        INSERT INTO portal.notification_deliveries
          (id, event_id, recipient_id, channel, notification_type, attempts, max_attempts)
        VALUES ('00000000-0000-4000-8000-0000000000d2',
                '00000000-0000-4000-8000-0000000000e2',
                (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
                'email','delay', 4, 5);
        UPDATE portal.notification_deliveries
        SET attempts = attempts + 1,
            status = CASE WHEN attempts + 1 >= max_attempts THEN 'dead' ELSE 'pending' END,
            next_attempt_at = NOW() + (LEAST(30 * POWER(2, attempts), 3600) || ' seconds')::INTERVAL
        WHERE id = '00000000-0000-4000-8000-0000000000d2'`,
      sql: `SELECT status AS v FROM portal.notification_deliveries
            WHERE id = '00000000-0000-4000-8000-0000000000d2'`,
      ok: (v) => v === "dead",
    },
    {
      name: "department master: WIO routing rejects unknown department",
      sql: `INSERT INTO ee.wio (wio_number, project_id, department_code, target_pio_date)
            SELECT 'WIO/26-27/999/NOPE', id, 'NOPE', CURRENT_DATE + 15
            FROM ee.projects LIMIT 1 RETURNING 'inserted' AS v`,
      expectError: true,
    },
    {
      name: "scheduler: auto-pilot system account seeded (L1)",
      sql: `SELECT access_level::TEXT AS v FROM public.users
            WHERE id = '00000000-0000-4000-8000-0000000000a0'`,
      ok: (v) => v === "L1",
    },
    {
      name: "scheduler: three jobs registered and enabled",
      sql: `SELECT (COUNT(*) = 3)::TEXT AS v FROM portal.scheduled_jobs
            WHERE enabled AND name IN ('notifications-dispatch','wio-clock','keka-sync')`,
      ok: (v) => v === "true",
    },
    {
      name: "scheduler: L1 permitted to read the scheduler resource",
      sql: `SELECT allowed::TEXT AS v FROM public.permissions
            WHERE access_level='L1' AND resource_type='scheduler'
              AND action_code='read' AND department_id IS NULL`,
      ok: (v) => v === "true",
    },
    {
      name: "scheduler: job_runs UNIQUE(job,slot) prevents double-fire",
      setupSql: `INSERT INTO portal.job_runs (job_id, job_name, scheduled_for)
                 SELECT id, name, '2026-07-08T07:00:00Z'
                 FROM portal.scheduled_jobs WHERE name='wio-clock'`,
      sql: `INSERT INTO portal.job_runs (job_id, job_name, scheduled_for)
            SELECT id, name, '2026-07-08T07:00:00Z'
            FROM portal.scheduled_jobs WHERE name='wio-clock' RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "scheduler: failed slot re-claims via ON CONFLICT (retry, attempt++)",
      setupSql: `INSERT INTO portal.job_runs
                   (job_id, job_name, scheduled_for, status, attempt, next_attempt_at)
                 SELECT id, name, '2026-07-08T00:00:00Z', 'failed', 1, NOW() - INTERVAL '1 minute'
                 FROM portal.scheduled_jobs WHERE name='notifications-dispatch'`,
      sql: `INSERT INTO portal.job_runs (job_id, job_name, scheduled_for, status, attempt, started_at)
            SELECT id, name, '2026-07-08T00:00:00Z', 'running', 1, NOW()
            FROM portal.scheduled_jobs WHERE name='notifications-dispatch'
            ON CONFLICT (job_id, scheduled_for) DO UPDATE
              SET status='running', attempt = portal.job_runs.attempt + 1
              WHERE portal.job_runs.status='failed' AND portal.job_runs.attempt < 3
            RETURNING attempt::TEXT AS v`,
      ok: (v) => v === "2",
    },
    {
      name: "scheduler: succeeded slot is NOT re-claimed",
      setupSql: `INSERT INTO portal.job_runs (job_id, job_name, scheduled_for, status, attempt)
                 SELECT id, name, '2026-07-08T01:00:00Z', 'succeeded', 1
                 FROM portal.scheduled_jobs WHERE name='keka-sync';
                 INSERT INTO portal.job_runs (job_id, job_name, scheduled_for, status, attempt, started_at)
                 SELECT id, name, '2026-07-08T01:00:00Z', 'running', 1, NOW()
                 FROM portal.scheduled_jobs WHERE name='keka-sync'
                 ON CONFLICT (job_id, scheduled_for) DO UPDATE
                   SET status='running'
                   WHERE portal.job_runs.status='failed'`,
      sql: `SELECT status AS v FROM portal.job_runs
            WHERE scheduled_for='2026-07-08T01:00:00Z'
              AND job_id=(SELECT id FROM portal.scheduled_jobs WHERE name='keka-sync')`,
      ok: (v) => v === "succeeded",
    },
    {
      name: "dead-letter: scheduler.job_dead routes to platform_admins",
      sql: `SELECT recipient_strategy AS v FROM portal.event_routes
            WHERE event_type = 'scheduler.job_dead'`,
      ok: (v) => v === "platform_admins",
    },
    {
      name: "dead-letter: platform_admins resolves founders + COO",
      sql: `SELECT (COUNT(*) >= 2)::TEXT AS v FROM public.users
            WHERE is_active AND (access_level::text = ANY(ARRAY['L0'])
              OR job_title ILIKE '%COO%' OR job_title ILIKE '%Chief Operating%'
              OR job_title ILIKE '%CTO%'  OR job_title ILIKE '%Chief Technology%'
              OR job_title ILIKE '%Platform Admin%')`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine 013: the four group/task tables exist",
      sql: `SELECT (COUNT(*) = 4)::TEXT AS v FROM information_schema.tables
            WHERE table_schema = 'portal'
              AND table_name IN ('workflow_groups','workflow_group_approvers',
                                 'workflow_tasks','workflow_delegations')`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine 013: workflow_groups UNIQUE(definition_code, group_no)",
      sql: `INSERT INTO portal.workflow_groups (definition_code, group_no, name)
            VALUES ('pio_approval', 1, 'dup') RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "wf-engine 014: pio_approval seeded as 3 groups",
      sql: `SELECT (COUNT(*) = 3)::TEXT AS v FROM portal.workflow_groups
            WHERE definition_code = 'pio_approval'`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine 014: pio groups mirror steps (quorum 1, fail_fast, emails)",
      sql: `SELECT (
              (SELECT bool_and(quorum=1 AND reject_policy='fail_fast')
                 FROM portal.workflow_groups WHERE definition_code='pio_approval')
              AND
              (SELECT COUNT(*)=3 FROM portal.workflow_group_approvers ga
                 JOIN portal.workflow_groups g ON g.id=ga.group_id
                 WHERE g.definition_code='pio_approval' AND ga.approver_ref LIKE '%@essentia.in')
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine: task decision is single-fire (CAS)",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000f3','pio_approval','pio',
                         '00000000-0000-4000-8000-0000000000f4', 1, 'pending');
                 INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
                 VALUES ('00000000-0000-4000-8000-0000000000f3', 1,
                         (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'));
                 UPDATE portal.workflow_tasks SET status='approved', acted_at=NOW()
                 WHERE instance_id='00000000-0000-4000-8000-0000000000f3'
                   AND group_no=1 AND status='pending'`,
      sql: `WITH cas AS (
              UPDATE portal.workflow_tasks SET status='approved'
              WHERE instance_id='00000000-0000-4000-8000-0000000000f3'
                AND group_no=1 AND status='pending' RETURNING id)
            SELECT (COUNT(*)=0)::TEXT AS v FROM cas`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine 013: workflow_tasks UNIQUE(instance, group, assignee)",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000f1','pio_approval','pio',
                         '00000000-0000-4000-8000-0000000000f2', 1, 'pending');
                 INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
                 VALUES ('00000000-0000-4000-8000-0000000000f1', 1,
                         (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'))`,
      sql: `INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
            VALUES ('00000000-0000-4000-8000-0000000000f1', 1,
                    (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'))
            RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "wf-engine 013: workflow_tasks status defaults to pending",
      sql: `SELECT status AS v FROM portal.workflow_tasks
            WHERE instance_id = '00000000-0000-4000-8000-0000000000f1' LIMIT 1`,
      ok: (v) => v === "pending",
    },
    {
      // PIO regression: the full 3-group chain (Khushpreet → Deepak → Hardesh)
      // materialize-task → CAS-approve → advance, exactly as the engine emits,
      // ends 'approved'. Mirrors the sequential single-approver PIO behaviour.
      name: "wf-engine: full PIO chain group 1→2→3 ends approved",
      setupSql: `
        INSERT INTO public.users (email, full_name, access_level, is_active) VALUES
          ('khushpreet.arora@essentia.in','Khushpreet Arora','L2',TRUE),
          ('deepak.jain@essentia.in','Deepak Jain','L1',TRUE),
          ('hardesh.chawla@essentia.in','Hardesh Chawla','L0',TRUE)
          ON CONFLICT (email) DO NOTHING;
        INSERT INTO portal.workflow_instances
          (id, workflow_code, resource_type, resource_id, current_step, status)
          VALUES ('00000000-0000-4000-8000-0000000000fa','pio_approval','pio',
                  '00000000-0000-4000-8000-0000000000fb', 1, 'pending');
        -- group 1 (Khushpreet)
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
          SELECT '00000000-0000-4000-8000-0000000000fa',1,id FROM public.users WHERE email='khushpreet.arora@essentia.in';
        UPDATE portal.workflow_tasks SET status='approved', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000fa' AND group_no=1 AND status='pending';
        UPDATE portal.workflow_instances SET current_step=2
          WHERE id='00000000-0000-4000-8000-0000000000fa' AND status='pending' AND current_step=1;
        -- group 2 (Deepak)
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
          SELECT '00000000-0000-4000-8000-0000000000fa',2,id FROM public.users WHERE email='deepak.jain@essentia.in';
        UPDATE portal.workflow_tasks SET status='approved', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000fa' AND group_no=2 AND status='pending';
        UPDATE portal.workflow_instances SET current_step=3
          WHERE id='00000000-0000-4000-8000-0000000000fa' AND status='pending' AND current_step=2;
        -- group 3 (Hardesh, final)
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
          SELECT '00000000-0000-4000-8000-0000000000fa',3,id FROM public.users WHERE email='hardesh.chawla@essentia.in';
        UPDATE portal.workflow_tasks SET status='approved', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000fa' AND group_no=3 AND status='pending';
        UPDATE portal.workflow_instances SET status='approved', completed_at=NOW()
          WHERE id='00000000-0000-4000-8000-0000000000fa' AND status='pending' AND current_step=3`,
      sql: `SELECT status AS v FROM portal.workflow_instances
            WHERE id = '00000000-0000-4000-8000-0000000000fa'`,
      ok: (v) => v === "approved",
    },
    {
      name: "wf-parallel: parallel_demo group 1 is a 2-of-3 quorum",
      sql: `SELECT (
              (SELECT quorum FROM portal.workflow_groups
                 WHERE definition_code='parallel_demo' AND group_no=1) = 2
              AND
              (SELECT COUNT(*) FROM portal.workflow_group_approvers ga
                 JOIN portal.workflow_groups g ON g.id=ga.group_id
                 WHERE g.definition_code='parallel_demo' AND g.group_no=1) = 3
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Parallel quorum: 2 of 3 approvals complete the group; the 3rd pending
      // task is skipped and the instance advances to group 2 (director).
      name: "wf-parallel: 2-of-3 approvals advance + skip the 3rd (task_id audited)",
      setupSql: `
        INSERT INTO portal.workflow_instances
          (id, workflow_code, resource_type, resource_id, current_step, status)
          VALUES ('00000000-0000-4000-8000-0000000000ba'::uuid,'parallel_demo','projects',
                  '00000000-0000-4000-8000-0000000000bb', 1, 'pending');
        -- materialize the 3 parallel tasks (COO, CRM TL, Site)
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id) VALUES
          ('00000000-0000-4000-8000-0000000000ba'::uuid, 1, '00000000-0000-4000-8000-000000000003'),
          ('00000000-0000-4000-8000-0000000000ba'::uuid, 1, '00000000-0000-4000-8000-000000000001'),
          ('00000000-0000-4000-8000-0000000000ba'::uuid, 1, '00000000-0000-4000-8000-000000000004');
        -- COO approves (1/2) — with task-linked action row
        WITH t AS (UPDATE portal.workflow_tasks SET status='approved', acted_by='00000000-0000-4000-8000-000000000003', acted_at=NOW()
                   WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid AND assignee_user_id='00000000-0000-4000-8000-000000000003' RETURNING id)
        INSERT INTO portal.workflow_actions (instance_id, task_id, step_no, group_no, action, acted_by)
          SELECT '00000000-0000-4000-8000-0000000000ba'::uuid, id, 1, 1, 'approve', '00000000-0000-4000-8000-000000000003' FROM t;
        -- CRM TL approves (2/2 -> quorum met)
        UPDATE portal.workflow_tasks SET status='approved', acted_by='00000000-0000-4000-8000-000000000001', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid AND assignee_user_id='00000000-0000-4000-8000-000000000001';
        -- quorum reached: skip remaining pending sibling (Site) + advance to group 2
        UPDATE portal.workflow_tasks SET status='skipped'
          WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid AND group_no=1 AND status='pending';
        UPDATE portal.workflow_instances SET current_step=2
          WHERE id='00000000-0000-4000-8000-0000000000ba'::uuid AND status='pending' AND current_step=1`,
      sql: `SELECT (
              (SELECT current_step FROM portal.workflow_instances WHERE id='00000000-0000-4000-8000-0000000000ba'::uuid) = 2
              AND
              (SELECT status FROM portal.workflow_tasks
                 WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid
                   AND assignee_user_id='00000000-0000-4000-8000-000000000004') = 'skipped'
              AND
              (SELECT COUNT(*) FROM portal.workflow_actions
                 WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid AND task_id IS NOT NULL) = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // fail_fast: one rejection in a parallel group rejects the instance and
      // skips the still-pending siblings.
      name: "wf-parallel: reject (fail_fast) rejects instance + skips siblings",
      setupSql: `
        INSERT INTO portal.workflow_instances
          (id, workflow_code, resource_type, resource_id, current_step, status)
          VALUES ('00000000-0000-4000-8000-0000000000bc'::uuid,'parallel_demo','projects',
                  '00000000-0000-4000-8000-0000000000bd', 1, 'pending');
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id) VALUES
          ('00000000-0000-4000-8000-0000000000bc'::uuid, 1, '00000000-0000-4000-8000-000000000003'),
          ('00000000-0000-4000-8000-0000000000bc'::uuid, 1, '00000000-0000-4000-8000-000000000001');
        UPDATE portal.workflow_tasks SET status='rejected', acted_by='00000000-0000-4000-8000-000000000003', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000bc'::uuid AND assignee_user_id='00000000-0000-4000-8000-000000000003';
        UPDATE portal.workflow_instances SET status='rejected', completed_at=NOW()
          WHERE id='00000000-0000-4000-8000-0000000000bc'::uuid AND status='pending' AND current_step=1;
        UPDATE portal.workflow_tasks SET status='skipped'
          WHERE instance_id='00000000-0000-4000-8000-0000000000bc'::uuid AND group_no=1 AND status='pending'`,
      sql: `SELECT (
              (SELECT status FROM portal.workflow_instances WHERE id='00000000-0000-4000-8000-0000000000bc'::uuid) = 'rejected'
              AND NOT EXISTS (SELECT 1 FROM portal.workflow_tasks
                 WHERE instance_id='00000000-0000-4000-8000-0000000000bc'::uuid AND status='pending')
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
  ];

  // RLS bypass note: PGlite runs as a superuser-ish single role, so the RLS
  // check forces the policy path with row_security and a non-owner role.
  await db.exec(`
    CREATE ROLE app_user NOLOGIN;
    GRANT USAGE ON SCHEMA ee, eh, factory, proc, portal, audit TO app_user;
    GRANT SELECT ON ALL TABLES IN SCHEMA ee, eh, public TO app_user;
  `);

  for (const check of checks) {
    try {
      if (check.setupSql) await db.exec(check.setupSql);
      if (check.asRestrictedRole) await db.exec("SET ROLE app_user");
      const res = await db.query(check.sql);
      if (check.asRestrictedRole) await db.exec("RESET ROLE");
      if (check.expectError) {
        console.error(`FAIL    ${check.name} — expected an error but the statement succeeded`);
        failed = true;
        continue;
      }
      const v = res.rows[0]?.v;
      if (check.ok(String(v))) {
        console.log(`PASS    ${check.name}`);
      } else {
        console.error(`FAIL    ${check.name} — got: ${v}`);
        failed = true;
      }
    } catch (err) {
      if (check.asRestrictedRole) await db.exec("RESET ROLE").catch(() => {});
      if (check.expectError) {
        console.log(`PASS    ${check.name}`);
      } else {
        console.error(`FAIL    ${check.name} — ${err.message}`);
        failed = true;
      }
    }
  }

  const tables = await db.query(`
    SELECT COUNT(*)::INT AS n FROM information_schema.tables
    WHERE table_schema IN ('public','ee','eh','factory','proc','portal','audit')
      AND table_type = 'BASE TABLE'
  `);
  console.log(`INFO    base tables created: ${tables.rows[0].n}`);
}

process.exit(failed ? 1 : 0);
