/**
 * Schema validation harness.
 *
 * Loads the full schema (and any seed files that exist) into PGlite —
 * embedded PostgreSQL with real semantics, including pgvector — so the SQL
 * is proven to load end-to-end without a local Postgres install.
 * Exit code 0 = everything loaded and smoke checks passed.
 *
 * Usage:  npm run validate            (from db/)
 *         node validate.mjs 001_essentia_schema.sql   (specific files)
 */
import { createDb, loadSqlFiles, resolveFiles } from "./lib.mjs";

const requested = process.argv.slice(2);
const files = resolveFiles(requested);

const db = createDb();
const failedFile = await loadSqlFiles(db, files);
let failed = Boolean(failedFile);

if (!failed) {
  // Smoke checks: document-number generators and the golden-thread trigger.
  const checks = [
    {
      name: "next_project_code format ED/YY-YY/NNN",
      sql: "SELECT next_project_code() AS v",
      ok: (v) => /^ED\/\d{2}-\d{2}\/\d{3}$/.test(v),
    },
    {
      name: "next_wio_number format WIO/YY-YY/NNN/DEPT",
      sql: "SELECT next_wio_number('ARCH') AS v",
      ok: (v) => /^WIO\/\d{2}-\d{2}\/\d{3}\/ARCH$/.test(v),
    },
    {
      name: "next_po_number format ESS/PO/YYYY/####",
      sql: "SELECT next_po_number() AS v",
      ok: (v) => /^ESS\/PO\/\d{4}\/\d{4}$/.test(v),
    },
    {
      name: "project_code auto-generated by trigger",
      sql: `
        WITH fam AS (
          INSERT INTO public.families (primary_contact) VALUES ('Validation Family')
          RETURNING id
        )
        INSERT INTO ee.projects (family_id, site_address)
        SELECT id, 'Validation Site' FROM fam
        RETURNING project_code AS v`,
      ok: (v) => /^ED\/\d{2}-\d{2}\/\d{3}$/.test(v),
    },
    {
      // Two statements: a data-modifying CTE is invisible to reads of the
      // same table later in the same statement (snapshot semantics).
      name: "ee.wio_clock view computes RAG",
      setupSql: `
        INSERT INTO ee.wio (wio_number, project_id, department_code, target_pio_date)
        SELECT next_wio_number('3D'), id, '3D', CURRENT_DATE + 3
        FROM ee.projects LIMIT 1`,
      sql: "SELECT clock_rag AS v FROM ee.wio_clock WHERE department_code = '3D'",
      ok: (v) => v === "amber",
    },
    {
      name: "views are security_invoker (RLS not bypassed through wio_clock)",
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.wio_clock",
      ok: (v) => v === "0",
      asRestrictedRole: true,
    },
    {
      name: "RLS: no user context => zero projects visible",
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "0",
      asRestrictedRole: true,
    },
    {
      name: "factory master: 9 stations = 7 active + 2 reserved",
      sql: `SELECT (COUNT(*) FILTER (WHERE status = 'active'))::TEXT || '/' ||
                   (COUNT(*) FILTER (WHERE status = 'reserved'))::TEXT AS v
            FROM factory.departments`,
      ok: (v) => v === "7/2",
    },
    {
      name: "RBAC: L3 read on billing is denied (§36)",
      sql: `SELECT allowed::TEXT AS v FROM public.permissions
            WHERE access_level = 'L3' AND resource_type = 'billing'
              AND action_code = 'read' AND department_id IS NULL`,
      ok: (v) => v === "false",
    },
    {
      name: "RBAC: L2 approve on wio is allowed, own dept",
      sql: `SELECT (allowed AND scope = 'own_dept')::TEXT AS v FROM public.permissions
            WHERE access_level = 'L2' AND resource_type = 'wio'
              AND action_code = 'approve' AND department_id IS NULL`,
      ok: (v) => v === "true",
    },
    {
      name: "RBAC: L2 approve on pio explicitly denied (§26 chain)",
      sql: `SELECT allowed::TEXT AS v FROM public.permissions
            WHERE access_level = 'L2' AND resource_type = 'pio'
              AND action_code = 'approve' AND department_id IS NULL`,
      ok: (v) => v === "false",
    },
    {
      name: "workflow: pio_approval has the 3-step chain",
      sql: `SELECT COUNT(*)::TEXT AS v FROM portal.workflow_steps
            WHERE workflow_code = 'pio_approval'`,
      ok: (v) => v === "3",
    },
    {
      name: "config: ai.provider resolves to anthropic",
      sql: `SELECT value #>> '{}' AS v FROM portal.app_config WHERE key = 'ai.provider'`,
      ok: (v) => v === "anthropic",
    },
    {
      name: "notifications: template library seeded",
      sql: `SELECT (COUNT(*) >= 10)::TEXT AS v FROM portal.notification_templates`,
      ok: (v) => v === "true",
    },
    // 4 = 3 fixture projects + the unassigned one created by the trigger
    // smoke check above — which only L0/L1 can see (no team membership).
    {
      name: "RLS matrix: L0 founder sees all 4 projects incl. unassigned",
      setupSql: `SELECT set_config('app.user_id', '00000000-0000-4000-8000-000000000002', false),
                        set_config('app.user_access_level', 'L0', false)`,
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "4",
      asRestrictedRole: true,
    },
    {
      name: "RLS matrix: L1 leadership sees all 4 projects incl. unassigned",
      setupSql: `SELECT set_config('app.user_id', '00000000-0000-4000-8000-000000000003', false),
                        set_config('app.user_access_level', 'L1', false)`,
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "4",
      asRestrictedRole: true,
    },
    {
      name: "RLS matrix: L2 TL sees exactly their 3 assigned projects",
      setupSql: `SELECT set_config('app.user_id', '00000000-0000-4000-8000-000000000001', false),
                        set_config('app.user_access_level', 'L2', false)`,
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "3",
      asRestrictedRole: true,
    },
    {
      name: "RLS matrix: unassigned L3 sees zero projects",
      setupSql: `SELECT set_config('app.user_id', '00000000-0000-4000-8000-000000000004', false),
                        set_config('app.user_access_level', 'L3', false)`,
      sql: "SELECT COUNT(*)::TEXT AS v FROM ee.projects",
      ok: (v) => v === "0",
      asRestrictedRole: true,
    },
    {
      name: "engine default-deny: L3 has no hr_access grant on users",
      sql: `SELECT COUNT(*)::TEXT AS v FROM public.permissions
            WHERE access_level = 'L3' AND resource_type = 'users'
              AND action_code = 'hr_access' AND allowed`,
      ok: (v) => v === "0",
    },
    {
      name: "audit trail carries actor_role",
      sql: `SELECT COUNT(*)::TEXT AS v FROM information_schema.columns
            WHERE table_schema = 'audit' AND table_name = 'log'
              AND column_name = 'actor_role'`,
      ok: (v) => v === "1",
    },
    {
      name: "auth: portal.sessions table exists",
      sql: `SELECT COUNT(*)::TEXT AS v FROM information_schema.tables
            WHERE table_schema = 'portal' AND table_name = 'sessions'`,
      ok: (v) => v === "1",
    },
    {
      name: "auth: config keys seeded (provider + timeouts)",
      sql: `SELECT COUNT(*)::TEXT AS v FROM portal.app_config
            WHERE key IN ('auth.provider','auth.session_absolute_minutes',
                          'auth.session_idle_minutes','auth.max_concurrent_sessions')`,
      ok: (v) => v === "4",
    },
    {
      // Intent: EVERY dev fixture user is loginable via the local password path.
      // (Asserting a fixed count broke whenever a fixture user was added.)
      name: "auth: dev users carry a scrypt password_hash",
      sql: `SELECT (COUNT(*) FILTER (WHERE password_hash LIKE '%:%') = COUNT(*)
                    AND COUNT(*) >= 4)::TEXT AS v
            FROM public.users WHERE email LIKE 'dev.%@essentia.in'`,
      ok: (v) => v === "true",
    },
    {
      name: "auth: essentia_app can write sessions (grant present)",
      sql: `SELECT has_table_privilege('essentia_app','portal.sessions','INSERT')::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Timeout predicates match validateSession(): a fresh session is
      // neither expired nor idle; an aged one is both flagged correctly.
      name: "auth: session timeout predicates (fresh / idle / expired)",
      setupSql: `
        INSERT INTO portal.sessions (user_id, token_hash, expires_at, last_seen_at) VALUES
          ((SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
           'fresh', NOW() + INTERVAL '8 hours', NOW()),
          ((SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
           'idle',  NOW() + INTERVAL '8 hours', NOW() - INTERVAL '2 hours'),
          ((SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
           'expired', NOW() - INTERVAL '1 minute', NOW())`,
      sql: `SELECT string_agg(token_hash || ':' ||
                     (expires_at <= NOW())::TEXT || '/' ||
                     (last_seen_at < NOW() - INTERVAL '60 minutes')::TEXT, ' ' ORDER BY token_hash) AS v
            FROM portal.sessions WHERE token_hash IN ('fresh','idle','expired')`,
      ok: (v) => v === "expired:true/false fresh:false/false idle:false/true",
    },
    {
      name: "auth: concurrent-cap query keeps newest N sessions",
      setupSql: `
        INSERT INTO portal.sessions (user_id, token_hash, expires_at, created_at)
        SELECT (SELECT id FROM public.users WHERE email='dev.coo@essentia.in'),
               'cap' || g, NOW() + INTERVAL '8 hours', NOW() + (g || ' seconds')::INTERVAL
        FROM generate_series(1,5) g`,
      sql: `WITH keep AS (
              SELECT id FROM portal.sessions
              WHERE user_id = (SELECT id FROM public.users WHERE email='dev.coo@essentia.in')
                AND revoked_at IS NULL
              ORDER BY created_at DESC LIMIT 3)
            SELECT COUNT(*)::TEXT AS v FROM portal.sessions
            WHERE user_id = (SELECT id FROM public.users WHERE email='dev.coo@essentia.in')
              AND revoked_at IS NULL AND id NOT IN (SELECT id FROM keep)`,
      ok: (v) => v === "2",
    },
    {
      name: "keka: portal.sync_runs table exists + grant",
      sql: `SELECT (
              EXISTS(SELECT 1 FROM information_schema.tables
                     WHERE table_schema='portal' AND table_name='sync_runs')
              AND has_table_privilege('essentia_app','portal.sync_runs','INSERT')
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "keka: PIO chain steps carry approver_email seeds",
      sql: `SELECT COUNT(*)::TEXT AS v FROM portal.workflow_steps
            WHERE workflow_code='pio_approval' AND approver_email IS NOT NULL`,
      ok: (v) => v === "3",
    },
    {
      name: "keka: department mapping populated (CRM → CRM_EE)",
      sql: `SELECT value->>'CRM' AS v FROM portal.app_config
            WHERE key='keka.department_mapping'`,
      ok: (v) => v === "CRM_EE",
    },
    {
      // Proves the "arm the approval chain" resolution: a synced approver
      // account links to workflow step 1.
      name: "keka: approver resolution links step 1 to Khushpreet",
      setupSql: `
        INSERT INTO public.users (email, full_name, access_level, is_active, keka_employee_id)
        VALUES ('khushpreet.arora@essentia.in','Khushpreet Arora','L2',TRUE,'K010')
        ON CONFLICT (email) DO NOTHING;
        UPDATE portal.workflow_steps s SET approver_user_id = u.id
        FROM public.users u
        WHERE s.approver_email IS NOT NULL AND lower(u.email)=lower(s.approver_email) AND u.is_active`,
      sql: `SELECT (approver_user_id IS NOT NULL)::TEXT AS v FROM portal.workflow_steps
            WHERE workflow_code='pio_approval' AND step_no=1`,
      ok: (v) => v === "true",
    },
    {
      // Locks in the param-typing fix: the workflow CAS advances a step
      // without the "inconsistent types for $2" failure.
      name: "workflow: CAS advance step 1 → 2 succeeds",
      setupSql: `
        WITH proj AS (SELECT id FROM ee.projects LIMIT 1)
        INSERT INTO portal.workflow_instances (workflow_code, resource_type, resource_id, current_step, status)
        SELECT 'pio_approval', 'pio', id, 1, 'pending' FROM proj;
        UPDATE portal.workflow_instances i
        SET status = 'pending', current_step = 2,
            completed_at = CASE WHEN FALSE::boolean THEN NOW() ELSE NULL END
        WHERE i.workflow_code = 'pio_approval' AND i.status = 'pending' AND i.current_step = 1`,
      sql: `SELECT current_step::TEXT AS v FROM portal.workflow_instances
            WHERE workflow_code = 'pio_approval' ORDER BY started_at DESC LIMIT 1`,
      ok: (v) => v === "2",
    },
    {
      name: "events: routing table seeded (>=10 routes)",
      sql: `SELECT (COUNT(*) >= 10)::TEXT AS v FROM portal.event_routes WHERE is_active`,
      ok: (v) => v === "true",
    },
    {
      name: "events: dedupe_key unique index prevents duplicates",
      setupSql: `INSERT INTO portal.events (event_type, category, dedupe_key)
                 VALUES ('t.dupe','system','DK-1')`,
      sql: `INSERT INTO portal.events (event_type, category, dedupe_key)
            VALUES ('t.dupe','system','DK-1') RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "deliveries: (event,recipient,channel) is unique",
      setupSql: `
        INSERT INTO portal.events (id, event_type, category)
        VALUES ('00000000-0000-4000-8000-0000000000e1','t.deliv','system');
        INSERT INTO portal.notification_deliveries (event_id, recipient_id, channel, notification_type)
        VALUES ('00000000-0000-4000-8000-0000000000e1',
                (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
                'in_app','system_alert')`,
      sql: `INSERT INTO portal.notification_deliveries (event_id, recipient_id, channel, notification_type)
            VALUES ('00000000-0000-4000-8000-0000000000e1',
                    (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
                    'in_app','system_alert') RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "delivery engine: exhausted retries transition to dead-letter",
      setupSql: `
        INSERT INTO portal.events (id, event_type, category)
        VALUES ('00000000-0000-4000-8000-0000000000e2','t.dead','system');
        INSERT INTO portal.notification_deliveries
          (id, event_id, recipient_id, channel, notification_type, attempts, max_attempts)
        VALUES ('00000000-0000-4000-8000-0000000000d2',
                '00000000-0000-4000-8000-0000000000e2',
                (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'),
                'email','delay', 4, 5);
        UPDATE portal.notification_deliveries
        SET attempts = attempts + 1,
            status = CASE WHEN attempts + 1 >= max_attempts THEN 'dead' ELSE 'pending' END,
            next_attempt_at = NOW() + (LEAST(30 * POWER(2, attempts), 3600) || ' seconds')::INTERVAL
        WHERE id = '00000000-0000-4000-8000-0000000000d2'`,
      sql: `SELECT status AS v FROM portal.notification_deliveries
            WHERE id = '00000000-0000-4000-8000-0000000000d2'`,
      ok: (v) => v === "dead",
    },
    {
      name: "department master: WIO routing rejects unknown department",
      sql: `INSERT INTO ee.wio (wio_number, project_id, department_code, target_pio_date)
            SELECT 'WIO/26-27/999/NOPE', id, 'NOPE', CURRENT_DATE + 15
            FROM ee.projects LIMIT 1 RETURNING 'inserted' AS v`,
      expectError: true,
    },
    {
      name: "scheduler: auto-pilot system account seeded (L1)",
      sql: `SELECT access_level::TEXT AS v FROM public.users
            WHERE id = '00000000-0000-4000-8000-0000000000a0'`,
      ok: (v) => v === "L1",
    },
    {
      name: "scheduler: three jobs registered and enabled",
      sql: `SELECT (COUNT(*) = 3)::TEXT AS v FROM portal.scheduled_jobs
            WHERE enabled AND name IN ('notifications-dispatch','wio-clock','keka-sync')`,
      ok: (v) => v === "true",
    },
    {
      name: "scheduler: L1 permitted to read the scheduler resource",
      sql: `SELECT allowed::TEXT AS v FROM public.permissions
            WHERE access_level='L1' AND resource_type='scheduler'
              AND action_code='read' AND department_id IS NULL`,
      ok: (v) => v === "true",
    },
    {
      name: "scheduler: job_runs UNIQUE(job,slot) prevents double-fire",
      setupSql: `INSERT INTO portal.job_runs (job_id, job_name, scheduled_for)
                 SELECT id, name, '2026-07-08T07:00:00Z'
                 FROM portal.scheduled_jobs WHERE name='wio-clock'`,
      sql: `INSERT INTO portal.job_runs (job_id, job_name, scheduled_for)
            SELECT id, name, '2026-07-08T07:00:00Z'
            FROM portal.scheduled_jobs WHERE name='wio-clock' RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "scheduler: failed slot re-claims via ON CONFLICT (retry, attempt++)",
      setupSql: `INSERT INTO portal.job_runs
                   (job_id, job_name, scheduled_for, status, attempt, next_attempt_at)
                 SELECT id, name, '2026-07-08T00:00:00Z', 'failed', 1, NOW() - INTERVAL '1 minute'
                 FROM portal.scheduled_jobs WHERE name='notifications-dispatch'`,
      sql: `INSERT INTO portal.job_runs (job_id, job_name, scheduled_for, status, attempt, started_at)
            SELECT id, name, '2026-07-08T00:00:00Z', 'running', 1, NOW()
            FROM portal.scheduled_jobs WHERE name='notifications-dispatch'
            ON CONFLICT (job_id, scheduled_for) DO UPDATE
              SET status='running', attempt = portal.job_runs.attempt + 1
              WHERE portal.job_runs.status='failed' AND portal.job_runs.attempt < 3
            RETURNING attempt::TEXT AS v`,
      ok: (v) => v === "2",
    },
    {
      name: "scheduler: succeeded slot is NOT re-claimed",
      setupSql: `INSERT INTO portal.job_runs (job_id, job_name, scheduled_for, status, attempt)
                 SELECT id, name, '2026-07-08T01:00:00Z', 'succeeded', 1
                 FROM portal.scheduled_jobs WHERE name='keka-sync';
                 INSERT INTO portal.job_runs (job_id, job_name, scheduled_for, status, attempt, started_at)
                 SELECT id, name, '2026-07-08T01:00:00Z', 'running', 1, NOW()
                 FROM portal.scheduled_jobs WHERE name='keka-sync'
                 ON CONFLICT (job_id, scheduled_for) DO UPDATE
                   SET status='running'
                   WHERE portal.job_runs.status='failed'`,
      sql: `SELECT status AS v FROM portal.job_runs
            WHERE scheduled_for='2026-07-08T01:00:00Z'
              AND job_id=(SELECT id FROM portal.scheduled_jobs WHERE name='keka-sync')`,
      ok: (v) => v === "succeeded",
    },
    {
      name: "dead-letter: scheduler.job_dead routes to platform_admins",
      sql: `SELECT recipient_strategy AS v FROM portal.event_routes
            WHERE event_type = 'scheduler.job_dead'`,
      ok: (v) => v === "platform_admins",
    },
    {
      name: "dead-letter: platform_admins resolves founders + COO",
      sql: `SELECT (COUNT(*) >= 2)::TEXT AS v FROM public.users
            WHERE is_active AND (access_level::text = ANY(ARRAY['L0'])
              OR job_title ILIKE '%COO%' OR job_title ILIKE '%Chief Operating%'
              OR job_title ILIKE '%CTO%'  OR job_title ILIKE '%Chief Technology%'
              OR job_title ILIKE '%Platform Admin%')`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine 013: the four group/task tables exist",
      sql: `SELECT (COUNT(*) = 4)::TEXT AS v FROM information_schema.tables
            WHERE table_schema = 'portal'
              AND table_name IN ('workflow_groups','workflow_group_approvers',
                                 'workflow_tasks','workflow_delegations')`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine 013: workflow_groups UNIQUE(definition_code, group_no)",
      sql: `INSERT INTO portal.workflow_groups (definition_code, group_no, name)
            VALUES ('pio_approval', 1, 'dup') RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "wf-engine 014: pio_approval seeded as 3 groups",
      sql: `SELECT (COUNT(*) = 3)::TEXT AS v FROM portal.workflow_groups
            WHERE definition_code = 'pio_approval'`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine 014: pio groups mirror steps (quorum 1, fail_fast, emails)",
      sql: `SELECT (
              (SELECT bool_and(quorum=1 AND reject_policy='fail_fast')
                 FROM portal.workflow_groups WHERE definition_code='pio_approval')
              AND
              (SELECT COUNT(*)=3 FROM portal.workflow_group_approvers ga
                 JOIN portal.workflow_groups g ON g.id=ga.group_id
                 WHERE g.definition_code='pio_approval' AND ga.approver_ref LIKE '%@essentia.in')
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine: task decision is single-fire (CAS)",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000f3','pio_approval','pio',
                         '00000000-0000-4000-8000-0000000000f4', 1, 'pending');
                 INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
                 VALUES ('00000000-0000-4000-8000-0000000000f3', 1,
                         (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'));
                 UPDATE portal.workflow_tasks SET status='approved', acted_at=NOW()
                 WHERE instance_id='00000000-0000-4000-8000-0000000000f3'
                   AND group_no=1 AND status='pending'`,
      sql: `WITH cas AS (
              UPDATE portal.workflow_tasks SET status='approved'
              WHERE instance_id='00000000-0000-4000-8000-0000000000f3'
                AND group_no=1 AND status='pending' RETURNING id)
            SELECT (COUNT(*)=0)::TEXT AS v FROM cas`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-engine 013: workflow_tasks UNIQUE(instance, group, assignee)",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000f1','pio_approval','pio',
                         '00000000-0000-4000-8000-0000000000f2', 1, 'pending');
                 INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
                 VALUES ('00000000-0000-4000-8000-0000000000f1', 1,
                         (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'))`,
      sql: `INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
            VALUES ('00000000-0000-4000-8000-0000000000f1', 1,
                    (SELECT id FROM public.users WHERE email='dev.crmtl@essentia.in'))
            RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "wf-engine 013: workflow_tasks status defaults to pending",
      sql: `SELECT status AS v FROM portal.workflow_tasks
            WHERE instance_id = '00000000-0000-4000-8000-0000000000f1' LIMIT 1`,
      ok: (v) => v === "pending",
    },
    {
      // PIO regression: the full 3-group chain (Khushpreet → Deepak → Hardesh)
      // materialize-task → CAS-approve → advance, exactly as the engine emits,
      // ends 'approved'. Mirrors the sequential single-approver PIO behaviour.
      name: "wf-engine: full PIO chain group 1→2→3 ends approved",
      setupSql: `
        INSERT INTO public.users (email, full_name, access_level, is_active) VALUES
          ('khushpreet.arora@essentia.in','Khushpreet Arora','L2',TRUE),
          ('deepak.jain@essentia.in','Deepak Jain','L1',TRUE),
          ('hardesh.chawla@essentia.in','Hardesh Chawla','L0',TRUE)
          ON CONFLICT (email) DO NOTHING;
        INSERT INTO portal.workflow_instances
          (id, workflow_code, resource_type, resource_id, current_step, status)
          VALUES ('00000000-0000-4000-8000-0000000000fa','pio_approval','pio',
                  '00000000-0000-4000-8000-0000000000fb', 1, 'pending');
        -- group 1 (Khushpreet)
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
          SELECT '00000000-0000-4000-8000-0000000000fa',1,id FROM public.users WHERE email='khushpreet.arora@essentia.in';
        UPDATE portal.workflow_tasks SET status='approved', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000fa' AND group_no=1 AND status='pending';
        UPDATE portal.workflow_instances SET current_step=2
          WHERE id='00000000-0000-4000-8000-0000000000fa' AND status='pending' AND current_step=1;
        -- group 2 (Deepak)
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
          SELECT '00000000-0000-4000-8000-0000000000fa',2,id FROM public.users WHERE email='deepak.jain@essentia.in';
        UPDATE portal.workflow_tasks SET status='approved', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000fa' AND group_no=2 AND status='pending';
        UPDATE portal.workflow_instances SET current_step=3
          WHERE id='00000000-0000-4000-8000-0000000000fa' AND status='pending' AND current_step=2;
        -- group 3 (Hardesh, final)
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id)
          SELECT '00000000-0000-4000-8000-0000000000fa',3,id FROM public.users WHERE email='hardesh.chawla@essentia.in';
        UPDATE portal.workflow_tasks SET status='approved', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000fa' AND group_no=3 AND status='pending';
        UPDATE portal.workflow_instances SET status='approved', completed_at=NOW()
          WHERE id='00000000-0000-4000-8000-0000000000fa' AND status='pending' AND current_step=3`,
      sql: `SELECT status AS v FROM portal.workflow_instances
            WHERE id = '00000000-0000-4000-8000-0000000000fa'`,
      ok: (v) => v === "approved",
    },
    {
      name: "wf-parallel: parallel_demo group 1 is a 2-of-3 quorum",
      sql: `SELECT (
              (SELECT quorum FROM portal.workflow_groups
                 WHERE definition_code='parallel_demo' AND group_no=1) = 2
              AND
              (SELECT COUNT(*) FROM portal.workflow_group_approvers ga
                 JOIN portal.workflow_groups g ON g.id=ga.group_id
                 WHERE g.definition_code='parallel_demo' AND g.group_no=1) = 3
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Parallel quorum: 2 of 3 approvals complete the group; the 3rd pending
      // task is skipped and the instance advances to group 2 (director).
      name: "wf-parallel: 2-of-3 approvals advance + skip the 3rd (task_id audited)",
      setupSql: `
        INSERT INTO portal.workflow_instances
          (id, workflow_code, resource_type, resource_id, current_step, status)
          VALUES ('00000000-0000-4000-8000-0000000000ba'::uuid,'parallel_demo','projects',
                  '00000000-0000-4000-8000-0000000000bb', 1, 'pending');
        -- materialize the 3 parallel tasks (COO, CRM TL, Site)
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id) VALUES
          ('00000000-0000-4000-8000-0000000000ba'::uuid, 1, '00000000-0000-4000-8000-000000000003'),
          ('00000000-0000-4000-8000-0000000000ba'::uuid, 1, '00000000-0000-4000-8000-000000000001'),
          ('00000000-0000-4000-8000-0000000000ba'::uuid, 1, '00000000-0000-4000-8000-000000000004');
        -- COO approves (1/2) — with task-linked action row
        WITH t AS (UPDATE portal.workflow_tasks SET status='approved', acted_by='00000000-0000-4000-8000-000000000003', acted_at=NOW()
                   WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid AND assignee_user_id='00000000-0000-4000-8000-000000000003' RETURNING id)
        INSERT INTO portal.workflow_actions (instance_id, task_id, step_no, group_no, action, acted_by)
          SELECT '00000000-0000-4000-8000-0000000000ba'::uuid, id, 1, 1, 'approve', '00000000-0000-4000-8000-000000000003' FROM t;
        -- CRM TL approves (2/2 -> quorum met)
        UPDATE portal.workflow_tasks SET status='approved', acted_by='00000000-0000-4000-8000-000000000001', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid AND assignee_user_id='00000000-0000-4000-8000-000000000001';
        -- quorum reached: skip remaining pending sibling (Site) + advance to group 2
        UPDATE portal.workflow_tasks SET status='skipped'
          WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid AND group_no=1 AND status='pending';
        UPDATE portal.workflow_instances SET current_step=2
          WHERE id='00000000-0000-4000-8000-0000000000ba'::uuid AND status='pending' AND current_step=1`,
      sql: `SELECT (
              (SELECT current_step FROM portal.workflow_instances WHERE id='00000000-0000-4000-8000-0000000000ba'::uuid) = 2
              AND
              (SELECT status FROM portal.workflow_tasks
                 WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid
                   AND assignee_user_id='00000000-0000-4000-8000-000000000004') = 'skipped'
              AND
              (SELECT COUNT(*) FROM portal.workflow_actions
                 WHERE instance_id='00000000-0000-4000-8000-0000000000ba'::uuid AND task_id IS NOT NULL) = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // fail_fast: one rejection in a parallel group rejects the instance and
      // skips the still-pending siblings.
      name: "wf-parallel: reject (fail_fast) rejects instance + skips siblings",
      setupSql: `
        INSERT INTO portal.workflow_instances
          (id, workflow_code, resource_type, resource_id, current_step, status)
          VALUES ('00000000-0000-4000-8000-0000000000bc'::uuid,'parallel_demo','projects',
                  '00000000-0000-4000-8000-0000000000bd', 1, 'pending');
        INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id) VALUES
          ('00000000-0000-4000-8000-0000000000bc'::uuid, 1, '00000000-0000-4000-8000-000000000003'),
          ('00000000-0000-4000-8000-0000000000bc'::uuid, 1, '00000000-0000-4000-8000-000000000001');
        UPDATE portal.workflow_tasks SET status='rejected', acted_by='00000000-0000-4000-8000-000000000003', acted_at=NOW()
          WHERE instance_id='00000000-0000-4000-8000-0000000000bc'::uuid AND assignee_user_id='00000000-0000-4000-8000-000000000003';
        UPDATE portal.workflow_instances SET status='rejected', completed_at=NOW()
          WHERE id='00000000-0000-4000-8000-0000000000bc'::uuid AND status='pending' AND current_step=1;
        UPDATE portal.workflow_tasks SET status='skipped'
          WHERE instance_id='00000000-0000-4000-8000-0000000000bc'::uuid AND group_no=1 AND status='pending'`,
      sql: `SELECT (
              (SELECT status FROM portal.workflow_instances WHERE id='00000000-0000-4000-8000-0000000000bc'::uuid) = 'rejected'
              AND NOT EXISTS (SELECT 1 FROM portal.workflow_tasks
                 WHERE instance_id='00000000-0000-4000-8000-0000000000bc'::uuid AND status='pending')
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-conditional 016: instances carry a context column (default {})",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000ca'::uuid,'pio_approval','pio',
                         '00000000-0000-4000-8000-0000000000cb', 1, 'pending')`,
      sql: `SELECT (context = '{}'::jsonb)::TEXT AS v FROM portal.workflow_instances
            WHERE id='00000000-0000-4000-8000-0000000000ca'::uuid`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-conditional: conditional_demo group 2 gates on amount > 5 Cr",
      sql: `SELECT (
              condition->>'field' = 'amount' AND condition->>'op' = '>'
              AND (condition->>'value')::bigint = 50000000
            )::TEXT AS v
            FROM portal.workflow_groups WHERE definition_code='conditional_demo' AND group_no=2`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-conditional: conditional_demo groups 1 and 3 always run (null condition)",
      sql: `SELECT (COUNT(*) = 2)::TEXT AS v FROM portal.workflow_groups
            WHERE definition_code='conditional_demo' AND group_no IN (1,3) AND condition IS NULL`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-delegation 017: reason column + 3 event routes seeded",
      sql: `SELECT (
              EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_schema='portal' AND table_name='workflow_delegations' AND column_name='reason')
              AND (SELECT COUNT(*) FROM portal.event_routes
                 WHERE event_type IN ('workflow.delegation_created','workflow.delegation_revoked','workflow.task_delegated')) = 3
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-delegation: active standing delegation resolves the delegate",
      setupSql: `INSERT INTO portal.workflow_delegations (delegator_id, delegate_id, from_date, to_date)
                 VALUES ('00000000-0000-4000-8000-000000000003',
                         '00000000-0000-4000-8000-000000000001',
                         CURRENT_DATE - 1, CURRENT_DATE + 1)`,
      sql: `SELECT wd.delegate_id::text AS v
            FROM portal.workflow_delegations wd
            JOIN public.users u ON u.id = wd.delegate_id AND u.is_active
            WHERE wd.delegator_id='00000000-0000-4000-8000-000000000003'
              AND wd.revoked_at IS NULL AND wd.from_date <= CURRENT_DATE AND wd.to_date >= CURRENT_DATE
            LIMIT 1`,
      ok: (v) => v === "00000000-0000-4000-8000-000000000001",
    },
    {
      name: "wf-delegation: expired window is not active",
      setupSql: `INSERT INTO portal.workflow_delegations (delegator_id, delegate_id, from_date, to_date)
                 VALUES ('00000000-0000-4000-8000-000000000004',
                         '00000000-0000-4000-8000-000000000001',
                         CURRENT_DATE - 10, CURRENT_DATE - 5)`,
      sql: `SELECT (COUNT(*) = 0)::TEXT AS v FROM portal.workflow_delegations
            WHERE delegator_id='00000000-0000-4000-8000-000000000004'
              AND revoked_at IS NULL AND from_date <= CURRENT_DATE AND to_date >= CURRENT_DATE`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-delegation: self-delegation rejected by table CHECK",
      sql: `INSERT INTO portal.workflow_delegations (delegator_id, delegate_id, from_date, to_date)
            VALUES ('00000000-0000-4000-8000-000000000003',
                    '00000000-0000-4000-8000-000000000003', CURRENT_DATE, CURRENT_DATE + 1)
            RETURNING 'x' AS v`,
      expectError: true,
    },
    {
      name: "wf-sla 018: workflow-timers job + 5 SLA event routes seeded",
      sql: `SELECT (
              EXISTS (SELECT 1 FROM portal.scheduled_jobs WHERE name='workflow-timers')
              AND (SELECT COUNT(*) FROM portal.event_routes WHERE event_type IN
                 ('workflow.sla_warning','workflow.sla_breached','workflow.escalated',
                  'workflow.task_reminded','workflow.timed_out')) = 5
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-sla: sla_demo group 1 has 24h SLA + 48h auto_approve timeout",
      sql: `SELECT (sla_hours=24 AND warn_hours=12 AND timeout_hours=48
                    AND timeout_action='auto_approve' AND reminder_hours=24)::TEXT AS v
            FROM portal.workflow_groups WHERE definition_code='sla_demo' AND group_no=1`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-sla sweep: past-deadline pending task is detected (breach + auto_approve timeout)",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000da'::uuid,'sla_demo','projects',
                         '00000000-0000-4000-8000-0000000000db', 1, 'pending');
                 INSERT INTO portal.workflow_tasks
                   (instance_id, group_no, assignee_user_id, sla_due_at, warn_at, timeout_at)
                 SELECT '00000000-0000-4000-8000-0000000000da'::uuid, 1,
                        '00000000-0000-4000-8000-000000000003',
                        NOW() - INTERVAL '1 hour', NOW() - INTERVAL '2 hour', NOW() - INTERVAL '1 hour'`,
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.workflow_tasks
                 WHERE status='pending' AND sla_due_at <= NOW()
                   AND instance_id='00000000-0000-4000-8000-0000000000da'::uuid) = 1
              AND
              (SELECT COUNT(*) FROM portal.workflow_tasks t
                 JOIN portal.workflow_instances i ON i.id=t.instance_id AND i.status='pending'
                 JOIN portal.workflow_groups g ON g.definition_code=i.workflow_code AND g.group_no=t.group_no
                 WHERE t.status='pending' AND t.timeout_at <= NOW() AND g.timeout_action='auto_approve'
                   AND t.instance_id='00000000-0000-4000-8000-0000000000da'::uuid) = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-notify 019: step_pending routes to workflow_task_assignee",
      sql: `SELECT recipient_strategy AS v FROM portal.event_routes
            WHERE event_type='workflow.step_pending'`,
      ok: (v) => v === "workflow_task_assignee",
    },
    {
      name: "wf-notify: task_assignee resolves the DELEGATE for a delegated task",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000ea'::uuid,'pio_approval','pio',
                         '00000000-0000-4000-8000-0000000000eb', 1, 'pending');
                 INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id, delegated_to_user_id)
                 VALUES ('00000000-0000-4000-8000-0000000000ea'::uuid, 1,
                         '00000000-0000-4000-8000-000000000003',
                         '00000000-0000-4000-8000-000000000001')`,
      sql: `SELECT DISTINCT COALESCE(t.delegated_to_user_id, t.assignee_user_id)::text AS v
            FROM portal.workflow_tasks t
            JOIN portal.workflow_instances i ON i.id = t.instance_id
            WHERE t.instance_id='00000000-0000-4000-8000-0000000000ea'::uuid
              AND t.group_no = i.current_step AND t.status='pending'`,
      ok: (v) => v === "00000000-0000-4000-8000-000000000001",
    },
    {
      name: "wf-advisory 020: versioned workflow_advisory prompt seeded + active",
      sql: `SELECT (is_active AND system_template <> '' AND user_template LIKE '%{{resourceRef}}%')::TEXT AS v
            FROM portal.ai_prompts WHERE code='workflow_advisory'`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-inbox: my-approvals shows the task for the effective approver (delegate), not the original",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000fc'::uuid,'pio_approval','pio',
                         '00000000-0000-4000-8000-0000000000fd', 1, 'pending');
                 INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id, delegated_to_user_id)
                 VALUES ('00000000-0000-4000-8000-0000000000fc'::uuid, 1,
                         '00000000-0000-4000-8000-000000000003',
                         '00000000-0000-4000-8000-000000000001')`,
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.workflow_tasks t
                 JOIN portal.workflow_instances i ON i.id=t.instance_id AND i.status='pending'
                 WHERE t.status='pending' AND t.group_no=i.current_step
                   AND COALESCE(t.delegated_to_user_id,t.assignee_user_id)='00000000-0000-4000-8000-000000000001'
                   AND t.instance_id='00000000-0000-4000-8000-0000000000fc'::uuid) = 1
              AND
              (SELECT COUNT(*) FROM portal.workflow_tasks t
                 JOIN portal.workflow_instances i ON i.id=t.instance_id AND i.status='pending'
                 WHERE t.status='pending' AND t.group_no=i.current_step
                   AND COALESCE(t.delegated_to_user_id,t.assignee_user_id)='00000000-0000-4000-8000-000000000003'
                   AND t.instance_id='00000000-0000-4000-8000-0000000000fc'::uuid) = 0
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "users search: active internal staff by name/email, excluding self",
      sql: `SELECT (COUNT(*) >= 1)::TEXT AS v FROM public.users u
            WHERE u.is_active AND NOT u.is_external
              AND u.id <> '00000000-0000-4000-8000-000000000002'
              AND (u.full_name ILIKE '%Dev%' OR u.email ILIKE '%dev%')`,
      ok: (v) => v === "true",
    },
    {
      // Friendly resource ref: a PIO instance resolves to "PIO <num> · <project_code>",
      // a projects instance to the bare project_code. Mirrors RESOURCE_REF_SQL in
      // frontend/lib/services/workflow-inbox.ts — keep the two in lockstep.
      name: "wf-inbox: resource ref resolves to friendly document numbers (PIO / project code)",
      setupSql: `INSERT INTO ee.pio (id, pio_number, project_id)
                 VALUES ('00000000-0000-4000-8000-0000000000ef'::uuid, 'ED/26-27/942',
                         '00000000-0000-4000-8000-00000000a001'::uuid);
                 INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES
                   ('00000000-0000-4000-8000-0000000000ee'::uuid,'pio_approval','pio',
                    '00000000-0000-4000-8000-0000000000ef'::uuid, 1, 'approved'),
                   ('00000000-0000-4000-8000-0000000000ed'::uuid,'pio_approval','projects',
                    '00000000-0000-4000-8000-00000000a001'::uuid, 1, 'approved')`,
      sql: `WITH ref AS (
              SELECT i.id,
                CASE
                  WHEN p.pio_number IS NOT NULL
                    THEN 'PIO ' || p.pio_number || COALESCE(' · ' || ppr.project_code, '')
                  WHEN pr.project_code IS NOT NULL THEN pr.project_code
                  ELSE NULL
                END AS resource_ref
              FROM portal.workflow_instances i
              LEFT JOIN ee.pio p        ON i.resource_type = 'pio'      AND p.id  = i.resource_id
              LEFT JOIN ee.projects ppr ON ppr.id = p.project_id
              LEFT JOIN ee.projects pr  ON i.resource_type = 'projects' AND pr.id = i.resource_id
            )
            SELECT (
              (SELECT resource_ref FROM ref WHERE id='00000000-0000-4000-8000-0000000000ee'::uuid)
                = 'PIO ED/26-27/942 · ED/26-27/901'
              AND
              (SELECT resource_ref FROM ref WHERE id='00000000-0000-4000-8000-0000000000ed'::uuid)
                = 'ED/26-27/901'
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Org-wide approvals oversight (COO): the LATERAL roll-up resolves one row
      // per pending instance with friendly ref, effective approver (delegate wins),
      // pending count and soonest SLA. Mirrors listApprovalsOverview in
      // frontend/lib/services/workflow-oversight.ts.
      name: "wf-oversight: org-wide roll-up resolves ref + waiting-on + pending count for a pending instance",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000e9'::uuid,'pio_approval','pio',
                         '00000000-0000-4000-8000-0000000000ef'::uuid, 1, 'pending');
                 INSERT INTO portal.workflow_tasks
                   (instance_id, group_no, assignee_user_id, delegated_to_user_id, status, sla_due_at)
                 VALUES ('00000000-0000-4000-8000-0000000000e9'::uuid, 1,
                         '00000000-0000-4000-8000-000000000003',
                         '00000000-0000-4000-8000-000000000001',
                         'pending', NOW() - INTERVAL '2 hours')`,
      sql: `SELECT (
              o.resource_ref = 'PIO ED/26-27/942 · ED/26-27/901'
              AND o.pending_count = 1
              AND o.waiting_on IS NOT NULL
              AND o.sla_due_at IS NOT NULL
            )::TEXT AS v
            FROM (
              SELECT
                CASE
                  WHEN p.pio_number IS NOT NULL
                    THEN 'PIO ' || p.pio_number || COALESCE(' · ' || ppr.project_code, '')
                  WHEN pr.project_code IS NOT NULL THEN pr.project_code
                  ELSE NULL
                END AS resource_ref,
                tt.sla_due_at, tt.pending_count, tt.waiting_on
              FROM portal.workflow_instances i
              JOIN portal.workflow_groups g
                ON g.definition_code = i.workflow_code AND g.group_no = i.current_step
              LEFT JOIN ee.pio p        ON i.resource_type = 'pio'      AND p.id  = i.resource_id
              LEFT JOIN ee.projects ppr ON ppr.id = p.project_id
              LEFT JOIN ee.projects pr  ON i.resource_type = 'projects' AND pr.id = i.resource_id
              CROSS JOIN LATERAL (
                SELECT MIN(t.sla_due_at)::text AS sla_due_at,
                       COUNT(*)::int AS pending_count,
                       string_agg(DISTINCT COALESCE(du.full_name, au.full_name), ', ') AS waiting_on
                FROM portal.workflow_tasks t
                LEFT JOIN public.users au ON au.id = t.assignee_user_id
                LEFT JOIN public.users du ON du.id = t.delegated_to_user_id
                WHERE t.instance_id = i.id AND t.group_no = i.current_step AND t.status = 'pending'
              ) tt
              WHERE i.id = '00000000-0000-4000-8000-0000000000e9'::uuid
            ) o`,
      ok: (v) => v === "true",
    },
    {
      // Founder Morning Brief #6 — open escalations requiring a founder: a pending
      // instance whose current approver is L0 counts; one whose approver is L1 does
      // not. Mirrors number6Escalations in frontend/lib/services/founder-brief.ts.
      name: "founder-brief: escalation count includes an L0-approver instance, excludes an L1 one",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES
                   ('00000000-0000-4000-8000-0000000000e8'::uuid,'pio_approval','pio',
                    '00000000-0000-4000-8000-0000000000d1'::uuid, 1, 'pending'),
                   ('00000000-0000-4000-8000-0000000000e7'::uuid,'pio_approval','projects',
                    '00000000-0000-4000-8000-0000000000d2'::uuid, 1, 'pending');
                 INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id, status)
                 VALUES
                   ('00000000-0000-4000-8000-0000000000e8'::uuid, 1, '00000000-0000-4000-8000-000000000002', 'pending'),
                   ('00000000-0000-4000-8000-0000000000e7'::uuid, 1, '00000000-0000-4000-8000-000000000003', 'pending')`,
      sql: `SELECT (
              (SELECT COUNT(DISTINCT i.id) FROM portal.workflow_instances i
                 JOIN portal.workflow_tasks t ON t.instance_id=i.id AND t.group_no=i.current_step AND t.status='pending'
                 JOIN public.users u ON u.id=COALESCE(t.delegated_to_user_id,t.assignee_user_id)
                 WHERE i.status='pending' AND u.access_level='L0'
                   AND i.id='00000000-0000-4000-8000-0000000000e8'::uuid) = 1
              AND
              (SELECT COUNT(DISTINCT i.id) FROM portal.workflow_instances i
                 JOIN portal.workflow_tasks t ON t.instance_id=i.id AND t.group_no=i.current_step AND t.status='pending'
                 JOIN public.users u ON u.id=COALESCE(t.delegated_to_user_id,t.assignee_user_id)
                 WHERE i.status='pending' AND u.access_level='L0'
                   AND i.id='00000000-0000-4000-8000-0000000000e7'::uuid) = 0
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Gate #6: the 6:30am auto-generation job is registered (db/021).
      name: "founder-brief 021: 'founder-morning-brief' job seeded daily at 06:30",
      sql: `SELECT (schedule_kind='daily' AND schedule_expr='06:30' AND enabled)::TEXT AS v
            FROM portal.scheduled_jobs WHERE name='founder-morning-brief'`,
      ok: (v) => v === "true",
    },
    {
      // The snapshot is one-per-day: a second generation the same day updates in
      // place, never a duplicate. Mirrors snapshotFounderBrief's ON CONFLICT upsert.
      name: "founder-brief: daily snapshot upserts in place (one row per day)",
      setupSql: `INSERT INTO portal.founder_brief_snapshots (brief_date, numbers)
                   VALUES (CURRENT_DATE, '[{"n":1}]'::jsonb)
                 ON CONFLICT (brief_date) DO UPDATE SET numbers=EXCLUDED.numbers, generated_at=NOW();
                 INSERT INTO portal.founder_brief_snapshots (brief_date, numbers)
                   VALUES (CURRENT_DATE, '[{"n":1},{"n":2}]'::jsonb)
                 ON CONFLICT (brief_date) DO UPDATE SET numbers=EXCLUDED.numbers, generated_at=NOW()`,
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.founder_brief_snapshots WHERE brief_date=CURRENT_DATE) = 1
              AND
              (SELECT jsonb_array_length(numbers) FROM portal.founder_brief_snapshots WHERE brief_date=CURRENT_DATE) = 2
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Gate #2: the Friday Weekly Pulse job is registered (db/022).
      name: "weekly-pulse 022: 'weekly-pulse-draft' job seeded daily at 05:00",
      sql: `SELECT (schedule_kind='daily' AND schedule_expr='05:00' AND enabled)::TEXT AS v
            FROM portal.scheduled_jobs WHERE name='weekly-pulse-draft'`,
      ok: (v) => v === "true",
    },
    {
      // Idempotency: a project that already has this week's weekly_pulse (fixture
      // seeds one for a001) is NOT in the "needs draft" set; one without (a002) is.
      // Mirrors the NOT EXISTS guard in draftWeeklyPulses.
      name: "weekly-pulse: auto-draft is one-per-project-per-week (skips a project already pulsed)",
      sql: `SELECT (
              (SELECT COUNT(*) FROM ee.projects p
                 WHERE p.is_active AND p.id='00000000-0000-4000-8000-00000000a001'::uuid
                   AND NOT EXISTS (
                     SELECT 1 FROM portal.communication_spine cs
                     WHERE cs.project_id=p.id AND cs.letter_type='weekly_pulse'
                       AND date_trunc('week', cs.created_at)=date_trunc('week', CURRENT_DATE))) = 0
              AND
              (SELECT COUNT(*) FROM ee.projects p
                 WHERE p.is_active AND p.id='00000000-0000-4000-8000-00000000a002'::uuid
                   AND NOT EXISTS (
                     SELECT 1 FROM portal.communication_spine cs
                     WHERE cs.project_id=p.id AND cs.letter_type='weekly_pulse'
                       AND date_trunc('week', cs.created_at)=date_trunc('week', CURRENT_DATE))) = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Gate #4: the 11:59pm sweep is registered (db/023), matching config
      // exit_protocol.fire_time = "23:59".
      name: "exit-protocol 023: 'exit-protocol' job seeded daily at 23:59",
      sql: `SELECT (schedule_kind='daily' AND schedule_expr='23:59' AND enabled)::TEXT AS v
            FROM portal.scheduled_jobs WHERE name='exit-protocol'`,
      ok: (v) => v === "true",
    },
    {
      // A recorded removal action is immutable-by-rerun: the UNIQUE(user, exit_date,
      // action) + ON CONFLICT DO NOTHING means a second sweep cannot overwrite an
      // honest 'not_wired' with a false 'completed'.
      name: "exit-protocol: an action is logged once per exit and a re-run cannot overwrite it",
      setupSql: `INSERT INTO portal.exit_protocol_actions (user_id, exit_date, action_code, status, detail)
                   VALUES ('00000000-0000-4000-8000-000000000004'::uuid, CURRENT_DATE,
                           'whatsapp_groups_removed', 'not_wired', 'first write')
                 ON CONFLICT (user_id, exit_date, action_code) DO NOTHING;
                 INSERT INTO portal.exit_protocol_actions (user_id, exit_date, action_code, status, detail)
                   VALUES ('00000000-0000-4000-8000-000000000004'::uuid, CURRENT_DATE,
                           'whatsapp_groups_removed', 'completed', 'second write')
                 ON CONFLICT (user_id, exit_date, action_code) DO NOTHING`,
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.exit_protocol_actions
                 WHERE user_id='00000000-0000-4000-8000-000000000004'::uuid
                   AND exit_date=CURRENT_DATE AND action_code='whatsapp_groups_removed') = 1
              AND
              (SELECT status FROM portal.exit_protocol_actions
                 WHERE user_id='00000000-0000-4000-8000-000000000004'::uuid
                   AND exit_date=CURRENT_DATE AND action_code='whatsapp_groups_removed') = 'not_wired'
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // 'pending' is a read-model state only (an exit that has not fired yet); it
      // must never be persisted as an action outcome.
      name: "exit-protocol: status CHECK rejects the read-model-only 'pending'",
      sql: `INSERT INTO portal.exit_protocol_actions (user_id, exit_date, action_code, status)
            VALUES ('00000000-0000-4000-8000-000000000004'::uuid, CURRENT_DATE - 1,
                    'sso_revoked', 'pending')`,
      expectError: true,
    },
    {
      // Gate #7: the same-day generation job is registered (db/024).
      name: "succession 024: 'succession-pack' job seeded daily at 06:00",
      sql: `SELECT (schedule_kind='daily' AND schedule_expr='06:00' AND enabled)::TEXT AS v
            FROM portal.scheduled_jobs WHERE name='succession-pack'`,
      ok: (v) => v === "true",
    },
    {
      // The default pack template ships as DATA, and every seeded section names a
      // source_kind the resolver registry knows.
      name: "succession 024: pack template seeded, all sections use a known source_kind",
      sql: `SELECT (
              COUNT(*) >= 6
              AND COUNT(*) FILTER (
                WHERE source_kind IN ('checklist','documents','static_note','project_ownership','pending_approvals')
              ) = COUNT(*)
            )::TEXT AS v
            FROM portal.succession_pack_sections WHERE is_active`,
      ok: (v) => v === "true",
    },
    {
      // THE POINT OF THE DESIGN: the pack's contents are configuration. HR adds a
      // section, drops one, and reorders — by editing rows. The generator reads
      // `WHERE is_active ORDER BY sort_order, code`, so this is exactly what a
      // regenerated pack would contain. No code changes here.
      name: "succession: pack contents are config-driven (HR row edits add/remove/reorder sections)",
      setupSql: `INSERT INTO portal.succession_pack_sections
                   (code, title, source_kind, params, sort_order, is_active)
                 VALUES ('hr_added_return_assets', 'Return of company assets', 'checklist',
                         '{"items": ["Return laptop and access card"]}'::jsonb, 15, TRUE)
                 ON CONFLICT (code) DO NOTHING;
                 UPDATE portal.succession_pack_sections SET is_active = FALSE
                 WHERE code = 'handover_documents'`,
      sql: `SELECT (
              -- the HR-added section is now part of the pack…
              EXISTS (SELECT 1 FROM portal.succession_pack_sections
                        WHERE code='hr_added_return_assets' AND is_active)
              -- …the deactivated one is out…
              AND NOT EXISTS (SELECT 1 FROM portal.succession_pack_sections
                                WHERE code='handover_documents' AND is_active)
              -- …and ordering follows sort_order, so HR controls position too.
              AND (SELECT string_agg(code, ',' ORDER BY sort_order, code)
                   FROM portal.succession_pack_sections
                   WHERE is_active AND sort_order <= 20)
                  = 'successor_briefing,hr_added_return_assets,project_ownership'
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // One pack per person per exit; a regenerate updates in place (that is how a
      // template change reaches an exit already on the books).
      name: "succession: pack is one-per-exit and regenerate updates in place",
      setupSql: `INSERT INTO portal.succession_packs (user_id, exit_date, sections)
                   VALUES ('00000000-0000-4000-8000-000000000005'::uuid, CURRENT_DATE,
                           '[{"code":"a"}]'::jsonb)
                 ON CONFLICT (user_id, exit_date) DO UPDATE SET sections = EXCLUDED.sections;
                 INSERT INTO portal.succession_packs (user_id, exit_date, sections)
                   VALUES ('00000000-0000-4000-8000-000000000005'::uuid, CURRENT_DATE,
                           '[{"code":"a"},{"code":"b"}]'::jsonb)
                 ON CONFLICT (user_id, exit_date) DO UPDATE
                   SET sections = EXCLUDED.sections, generated_at = NOW()`,
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.succession_packs
                 WHERE user_id='00000000-0000-4000-8000-000000000005'::uuid
                   AND exit_date=CURRENT_DATE) = 1
              AND
              (SELECT jsonb_array_length(sections) FROM portal.succession_packs
                 WHERE user_id='00000000-0000-4000-8000-000000000005'::uuid
                   AND exit_date=CURRENT_DATE) = 2
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // WES §9/§10: standing delegations expire automatically via the scheduler.
      name: "wf-delegation 025: expiry job (daily 00:05) + expired event route + expired_at column",
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.scheduled_jobs
                 WHERE name='delegation-expiry' AND schedule_kind='daily'
                   AND schedule_expr='00:05' AND enabled) = 1
              AND (SELECT COUNT(*) FROM portal.event_routes
                     WHERE event_type='workflow.delegation_expired') = 1
              AND (SELECT COUNT(*) FROM information_schema.columns
                     WHERE table_schema='portal' AND table_name='workflow_delegations'
                       AND column_name='expired_at') = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // The sweep stamps ONLY delegations whose window has closed and that are
      // neither revoked nor already stamped. Mirrors expireStandingDelegations.
      name: "wf-delegation: expiry sweep stamps the lapsed one, leaves active and revoked untouched",
      setupSql: `INSERT INTO portal.workflow_delegations
                   (id, delegator_id, delegate_id, from_date, to_date, revoked_at) VALUES
                   ('00000000-0000-4000-8000-0000000000c1'::uuid,
                    '00000000-0000-4000-8000-000000000003','00000000-0000-4000-8000-000000000004',
                    CURRENT_DATE - 10, CURRENT_DATE - 1, NULL),
                   ('00000000-0000-4000-8000-0000000000c2'::uuid,
                    '00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000001',
                    CURRENT_DATE - 1, CURRENT_DATE + 5, NULL),
                   ('00000000-0000-4000-8000-0000000000c3'::uuid,
                    '00000000-0000-4000-8000-000000000004','00000000-0000-4000-8000-000000000001',
                    CURRENT_DATE - 10, CURRENT_DATE - 2, NOW());
                 UPDATE portal.workflow_delegations SET expired_at = NOW()
                 WHERE revoked_at IS NULL AND expired_at IS NULL AND to_date < CURRENT_DATE`,
      sql: `SELECT (
              (SELECT expired_at IS NOT NULL FROM portal.workflow_delegations
                 WHERE id='00000000-0000-4000-8000-0000000000c1'::uuid)
              AND (SELECT expired_at IS NULL FROM portal.workflow_delegations
                     WHERE id='00000000-0000-4000-8000-0000000000c2'::uuid)
              AND (SELECT expired_at IS NULL FROM portal.workflow_delegations
                     WHERE id='00000000-0000-4000-8000-0000000000c3'::uuid)
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Idempotent: a second pass has nothing left to stamp (converges).
      name: "wf-delegation: expiry sweep is idempotent (nothing left to stamp on a second pass)",
      setupSql: `UPDATE portal.workflow_delegations SET expired_at = NOW()
                 WHERE revoked_at IS NULL AND expired_at IS NULL AND to_date < CURRENT_DATE`,
      sql: `SELECT (COUNT(*) = 0)::TEXT AS v
            FROM portal.workflow_delegations
            WHERE revoked_at IS NULL AND expired_at IS NULL AND to_date < CURRENT_DATE`,
      ok: (v) => v === "true",
    },
    {
      // Enforcement must NOT depend on the sweep: a lapsed delegation stops
      // resolving because of the date window, stamped or not.
      name: "wf-delegation: a lapsed delegation never resolves, independent of the expiry sweep",
      setupSql: `INSERT INTO portal.workflow_delegations
                   (id, delegator_id, delegate_id, from_date, to_date) VALUES
                   ('00000000-0000-4000-8000-0000000000c4'::uuid,
                    '00000000-0000-4000-8000-000000000005','00000000-0000-4000-8000-000000000001',
                    CURRENT_DATE - 10, CURRENT_DATE - 1)`,
      sql: `SELECT (COUNT(*) = 0)::TEXT AS v
            FROM portal.workflow_delegations wd
            JOIN public.users u ON u.id = wd.delegate_id AND u.is_active
            WHERE wd.delegator_id = '00000000-0000-4000-8000-000000000005'::uuid
              AND wd.revoked_at IS NULL
              AND wd.from_date <= CURRENT_DATE AND wd.to_date >= CURRENT_DATE`,
      ok: (v) => v === "true",
    },
    {
      name: "wf-sla 026: fire-once stamps (sla_warned_at / sla_breached_at) exist on tasks",
      sql: `SELECT (COUNT(*) = 2)::TEXT AS v
            FROM information_schema.columns
            WHERE table_schema='portal' AND table_name='workflow_tasks'
              AND column_name IN ('sla_warned_at','sla_breached_at')`,
      ok: (v) => v === "true",
    },
    {
      // The audit-flooding fix: a breached task is selected by the sweep ONCE.
      // Before db/026 the same task was re-selected on every 5-min tick, writing
      // a WORKFLOW_SLA_BREACH audit row each time (~288/day).
      name: "wf-sla: a breached task is swept once — the second pass selects nothing",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000000000b1'::uuid,'pio_approval','pio',
                         '00000000-0000-4000-8000-0000000000b2'::uuid, 1, 'pending');
                 INSERT INTO portal.workflow_tasks
                   (id, instance_id, group_no, assignee_user_id, status, sla_due_at)
                 VALUES ('00000000-0000-4000-8000-0000000000b3'::uuid,
                         '00000000-0000-4000-8000-0000000000b1'::uuid, 1,
                         '00000000-0000-4000-8000-000000000003', 'pending', NOW() - INTERVAL '2 hours');
                 -- pass 1: select the breached task and stamp it (what the sweep does)
                 UPDATE portal.workflow_tasks SET sla_breached_at = NOW()
                 WHERE status='pending' AND sla_breached_at IS NULL
                   AND sla_due_at IS NOT NULL AND sla_due_at <= NOW()`,
      sql: `SELECT (
              -- it WAS stamped by pass 1…
              (SELECT sla_breached_at IS NOT NULL FROM portal.workflow_tasks
                 WHERE id='00000000-0000-4000-8000-0000000000b3'::uuid)
              -- …and pass 2 finds nothing left to fire.
              AND (SELECT COUNT(*) FROM portal.workflow_tasks
                     WHERE status='pending' AND sla_breached_at IS NULL
                       AND sla_due_at IS NOT NULL AND sla_due_at <= NOW()) = 0
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Escalation transfers ownership (WES §8): the original is marked and the
      // target gets a task they can actually act on.
      name: "wf-sla: escalation marks the original 'escalated' and materialises the target's task",
      setupSql: `UPDATE portal.workflow_tasks SET status='escalated'
                 WHERE id='00000000-0000-4000-8000-0000000000b3'::uuid AND status='pending';
                 INSERT INTO portal.workflow_tasks (instance_id, group_no, assignee_user_id, assigned_at)
                 VALUES ('00000000-0000-4000-8000-0000000000b1'::uuid, 1,
                         '00000000-0000-4000-8000-000000000002', NOW())
                 ON CONFLICT (instance_id, group_no, assignee_user_id) DO UPDATE
                   SET status='pending', assigned_at=NOW()
                   WHERE portal.workflow_tasks.status NOT IN ('approved','rejected')`,
      sql: `SELECT (
              (SELECT status FROM portal.workflow_tasks
                 WHERE id='00000000-0000-4000-8000-0000000000b3'::uuid) = 'escalated'
              AND EXISTS (SELECT 1 FROM portal.workflow_tasks
                            WHERE instance_id='00000000-0000-4000-8000-0000000000b1'::uuid
                              AND assignee_user_id='00000000-0000-4000-8000-000000000002'
                              AND status='pending'
                              AND sla_due_at IS NULL)
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Frontend read model: settled (approved/rejected) workflows for the
      // dashboard's completed + recently-rejected sections. Mirrors
      // listSettledWorkflows in frontend/lib/services/workflow-oversight.ts.
      name: "wf-dashboard: settled-workflow query returns finished instances with decider + starter",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status,
                    started_by, completed_at)
                 VALUES
                   ('00000000-0000-4000-8000-0000000000d5'::uuid,'pio_approval','projects',
                    '00000000-0000-4000-8000-00000000a001'::uuid, 1, 'approved',
                    '00000000-0000-4000-8000-000000000003', NOW()),
                   ('00000000-0000-4000-8000-0000000000d6'::uuid,'pio_approval','projects',
                    '00000000-0000-4000-8000-00000000a002'::uuid, 1, 'rejected',
                    '00000000-0000-4000-8000-000000000003', NOW() - INTERVAL '1 hour');
                 INSERT INTO portal.workflow_actions
                   (instance_id, step_no, group_no, action, acted_by)
                 VALUES ('00000000-0000-4000-8000-0000000000d5'::uuid, 1, 1, 'approve',
                         '00000000-0000-4000-8000-000000000002')`,
      sql: `SELECT (
              -- both settled rows come back, newest-completed first…
              (SELECT COUNT(*) FROM (
                 SELECT i.id FROM portal.workflow_instances i
                 WHERE i.status = ANY(ARRAY['approved','rejected'])
                   AND i.id IN ('00000000-0000-4000-8000-0000000000d5'::uuid,
                                '00000000-0000-4000-8000-0000000000d6'::uuid)) x) = 2
              -- …the starter resolves…
              AND (SELECT sb.full_name IS NOT NULL
                     FROM portal.workflow_instances i
                     LEFT JOIN public.users sb ON sb.id = i.started_by
                     WHERE i.id='00000000-0000-4000-8000-0000000000d5'::uuid)
              -- …and the LATERAL picks the most recent decider.
              AND (SELECT la.actor_name
                     FROM portal.workflow_instances i
                     LEFT JOIN LATERAL (
                       SELECT u.full_name AS actor_name
                       FROM portal.workflow_actions wa
                       LEFT JOIN public.users u ON u.id = wa.acted_by
                       WHERE wa.instance_id = i.id
                       ORDER BY wa.acted_at DESC LIMIT 1
                     ) la ON TRUE
                     WHERE i.id='00000000-0000-4000-8000-0000000000d5'::uuid) IS NOT NULL
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Mirrors getSlaMonitorCounts — aggregates over the timer state the sweep
      // already maintains (screen 8). Read-only.
      name: "wf-sla-monitor: counts split approaching / breached / escalated / timed-out",
      sql: `SELECT (
              approaching >= 0 AND breached >= 0 AND escalated >= 1 AND timed_out >= 0
            )::TEXT AS v
            FROM (
              SELECT
                COUNT(*) FILTER (WHERE status='pending' AND sla_warned_at IS NOT NULL
                                   AND sla_breached_at IS NULL)::int AS approaching,
                COUNT(*) FILTER (WHERE status='pending' AND sla_breached_at IS NOT NULL)::int AS breached,
                COUNT(*) FILTER (WHERE status='escalated')::int AS escalated,
                COUNT(*) FILTER (WHERE status='timed_out')::int AS timed_out
              FROM portal.workflow_tasks
            ) c`,
      ok: (v) => v === "true",
    },
    {
      // Mirrors getSlaTrend — the series is only truthful because the sweep
      // stamps sla_warned_at / sla_breached_at (db/026). Zero-filled, no gaps.
      name: "wf-sla-monitor: trend returns one zero-filled row per day",
      sql: `SELECT (COUNT(*) = 14 AND COUNT(*) FILTER (WHERE warnings IS NULL OR breaches IS NULL) = 0)::TEXT AS v
            FROM (
              SELECT to_char(d.day,'YYYY-MM-DD') AS day,
                     COALESCE(w.n,0)::int AS warnings, COALESCE(b.n,0)::int AS breaches
              FROM generate_series(CURRENT_DATE - 13, CURRENT_DATE, INTERVAL '1 day') AS d(day)
              LEFT JOIN (SELECT date_trunc('day', sla_warned_at) AS day, COUNT(*) AS n
                         FROM portal.workflow_tasks WHERE sla_warned_at IS NOT NULL GROUP BY 1) w
                ON w.day = d.day
              LEFT JOIN (SELECT date_trunc('day', sla_breached_at) AS day, COUNT(*) AS n
                         FROM portal.workflow_tasks WHERE sla_breached_at IS NOT NULL GROUP BY 1) b
                ON b.day = d.day
              ORDER BY d.day
            ) t`,
      ok: (v) => v === "true",
    },
    {
      // Mirrors listAllDelegations — the org-wide admin read (screen 7), as
      // opposed to listDelegations which is scoped to the caller.
      name: "wf-delegation: org-wide listing returns delegations across all users",
      sql: `SELECT (COUNT(*) >= 2)::TEXT AS v
            FROM portal.workflow_delegations wd
            JOIN public.users du ON du.id = wd.delegator_id
            JOIN public.users de ON de.id = wd.delegate_id
            LEFT JOIN portal.workflow_definitions d ON d.code = wd.definition_code`,
      ok: (v) => v === "true",
    },
    {
      // Screen 2 Audit tab — the read model unifies THREE existing sources for
      // one instance. The load-bearing link is the one the task hinged on: a
      // notification delivery joins back to the instance through its event's
      // payload.instanceId. Mirrors getWorkflowAudit.
      name: "wf-audit: aggregation links approvals + audit.log + notification deliveries to one instance",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000cafe0001'::uuid,'pio_approval','pio',
                         '00000000-0000-4000-8000-0000cafe0002'::uuid, 1, 'pending');
                 INSERT INTO portal.workflow_actions (instance_id, step_no, group_no, action, acted_by)
                 VALUES ('00000000-0000-4000-8000-0000cafe0001'::uuid, 1, 1, 'approve',
                         '00000000-0000-4000-8000-000000000003');
                 INSERT INTO audit.log (user_id, actor_role, action, resource_type, resource_id, new_values)
                 VALUES ('00000000-0000-4000-8000-0000000000a0','L1','WORKFLOW_SLA_BREACH','workflows',
                         '00000000-0000-4000-8000-0000cafe0001'::uuid,
                         '{"taskId":"t","escalatedTo":"00000000-0000-4000-8000-000000000002"}'::jsonb);
                 INSERT INTO portal.events (id, event_type, category, entity_type, entity_id, payload)
                 VALUES ('00000000-0000-4000-8000-0000cafe0003'::uuid,'workflow.step_pending','approval',
                         'pio','00000000-0000-4000-8000-0000cafe0002'::uuid,
                         '{"instanceId":"00000000-0000-4000-8000-0000cafe0001"}'::jsonb);
                 INSERT INTO portal.notification_deliveries
                   (event_id, recipient_id, channel, notification_type, status)
                 VALUES ('00000000-0000-4000-8000-0000cafe0003'::uuid,
                         '00000000-0000-4000-8000-000000000003','in_app','assignment','sent')`,
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.workflow_actions
                 WHERE instance_id='00000000-0000-4000-8000-0000cafe0001'::uuid) = 1
              AND (SELECT COUNT(*) FROM audit.log l
                     WHERE l.action LIKE 'WORKFLOW\\_%'
                       AND l.action NOT IN ('WORKFLOW_APPROVE','WORKFLOW_REJECT')
                       AND l.resource_type='workflows'
                       AND l.resource_id::text='00000000-0000-4000-8000-0000cafe0001') = 1
              AND (SELECT COUNT(*)
                     FROM portal.events e
                     JOIN portal.notification_deliveries nd ON nd.event_id = e.id
                     WHERE e.payload->>'instanceId' = '00000000-0000-4000-8000-0000cafe0001') = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Screen 7 — listAllDelegations derives STATUS from existing timestamps
      // only (no stored status column): revoked wins, then expiry (stamped OR
      // window passed), then a future window, else live. Four fixtures, one per
      // branch, must classify exactly.
      name: "wf-delegation: status derived from timestamps (active/scheduled/expired/revoked)",
      setupSql: `INSERT INTO portal.workflow_delegations
                   (id, delegator_id, delegate_id, from_date, to_date, revoked_at, expired_at, created_by) VALUES
                 ('00000000-0000-4000-8000-0000beef0101'::uuid,'00000000-0000-4000-8000-0000000000a0',
                  '00000000-0000-4000-8000-000000000003', CURRENT_DATE-1, CURRENT_DATE+1, NULL, NULL,
                  '00000000-0000-4000-8000-0000000000a0'),
                 ('00000000-0000-4000-8000-0000beef0102'::uuid,'00000000-0000-4000-8000-0000000000a0',
                  '00000000-0000-4000-8000-000000000003', CURRENT_DATE+2, CURRENT_DATE+5, NULL, NULL,
                  '00000000-0000-4000-8000-0000000000a0'),
                 ('00000000-0000-4000-8000-0000beef0103'::uuid,'00000000-0000-4000-8000-0000000000a0',
                  '00000000-0000-4000-8000-000000000003', CURRENT_DATE-5, CURRENT_DATE-1, NULL, NULL,
                  '00000000-0000-4000-8000-0000000000a0'),
                 ('00000000-0000-4000-8000-0000beef0104'::uuid,'00000000-0000-4000-8000-0000000000a0',
                  '00000000-0000-4000-8000-000000000003', CURRENT_DATE-1, CURRENT_DATE+1, NOW(), NULL,
                  '00000000-0000-4000-8000-0000000000a0')`,
      sql: `SELECT (COUNT(*) = 4 AND COUNT(*) FILTER (WHERE derived = expected) = 4)::TEXT AS v
            FROM (
              SELECT wd.id,
                CASE
                  WHEN wd.revoked_at IS NOT NULL THEN 'revoked'
                  WHEN wd.expired_at IS NOT NULL OR wd.to_date < CURRENT_DATE THEN 'expired'
                  WHEN wd.from_date > CURRENT_DATE THEN 'scheduled'
                  ELSE 'active'
                END AS derived,
                x.expected
              FROM portal.workflow_delegations wd
              JOIN (VALUES
                ('00000000-0000-4000-8000-0000beef0101'::uuid,'active'),
                ('00000000-0000-4000-8000-0000beef0102'::uuid,'scheduled'),
                ('00000000-0000-4000-8000-0000beef0103'::uuid,'expired'),
                ('00000000-0000-4000-8000-0000beef0104'::uuid,'revoked')
              ) x(id, expected) ON x.id = wd.id
            ) t`,
      ok: (v) => v === "true",
    },
    {
      // Screen 7 — getDelegationDetail aggregates EXISTING data for one standing
      // delegation: (1) tasks it routed are workflow_tasks where the delegate
      // stands in for the delegator, in scope; (2) audit history is audit.log
      // rows keyed to the delegation id; (3) notification history is events for
      // this delegation → deliveries. The scope filter must exclude other codes.
      name: "wf-delegation: detail aggregates routed tasks (scoped), audit and notification history",
      setupSql: `INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000beef0201'::uuid,'pio_approval','pio',
                         '00000000-0000-4000-8000-0000beef0202'::uuid, 1, 'pending');
                 INSERT INTO portal.workflow_tasks
                   (instance_id, group_no, assignee_user_id, delegated_to_user_id, status)
                 VALUES ('00000000-0000-4000-8000-0000beef0201'::uuid, 1,
                         '00000000-0000-4000-8000-0000000000a0','00000000-0000-4000-8000-000000000003','pending');
                 INSERT INTO portal.workflow_delegations
                   (id, delegator_id, delegate_id, from_date, to_date, definition_code, created_by)
                 VALUES ('00000000-0000-4000-8000-0000beef0210'::uuid,'00000000-0000-4000-8000-0000000000a0',
                         '00000000-0000-4000-8000-000000000003', CURRENT_DATE-1, CURRENT_DATE+5,'pio_approval',
                         '00000000-0000-4000-8000-0000000000a0');
                 INSERT INTO audit.log (user_id, actor_role, action, resource_type, resource_id, new_values)
                 VALUES ('00000000-0000-4000-8000-0000000000a0','L1','WORKFLOW_DELEGATION_CREATE','workflows',
                         '00000000-0000-4000-8000-0000beef0210'::uuid,
                         '{"delegationId":"00000000-0000-4000-8000-0000beef0210"}'::jsonb);
                 INSERT INTO portal.events (id, event_type, category, entity_type, entity_id, payload)
                 VALUES ('00000000-0000-4000-8000-0000beef0220'::uuid,'workflow.delegation_created','approval',
                         'workflow_delegation','00000000-0000-4000-8000-0000beef0210'::uuid,'{}'::jsonb);
                 INSERT INTO portal.notification_deliveries
                   (event_id, recipient_id, channel, notification_type, status)
                 VALUES ('00000000-0000-4000-8000-0000beef0220'::uuid,
                         '00000000-0000-4000-8000-000000000003','in_app','assignment','sent')`,
      sql: `SELECT (
              EXISTS (
                SELECT 1 FROM portal.workflow_tasks t
                JOIN portal.workflow_instances i ON i.id = t.instance_id
                WHERE t.instance_id = '00000000-0000-4000-8000-0000beef0201'::uuid
                  AND t.assignee_user_id='00000000-0000-4000-8000-0000000000a0'
                  AND t.delegated_to_user_id='00000000-0000-4000-8000-000000000003'
                  AND t.status='pending' AND i.status='pending'
                  AND (NULL IS NULL OR i.workflow_code='pio_approval')
              )
              AND NOT EXISTS (
                SELECT 1 FROM portal.workflow_tasks t
                JOIN portal.workflow_instances i ON i.id = t.instance_id
                WHERE t.instance_id = '00000000-0000-4000-8000-0000beef0201'::uuid
                  AND t.assignee_user_id='00000000-0000-4000-8000-0000000000a0'
                  AND t.delegated_to_user_id='00000000-0000-4000-8000-000000000003'
                  AND i.workflow_code='a_different_scope'
              )
              AND (SELECT COUNT(*) FROM audit.log l
                     WHERE l.resource_type='workflows'
                       AND l.resource_id::text='00000000-0000-4000-8000-0000beef0210'
                       AND l.action LIKE 'WORKFLOW\\_DELEGATION%') = 1
              AND (SELECT COUNT(*)
                     FROM portal.events e
                     JOIN portal.notification_deliveries nd ON nd.event_id = e.id
                     WHERE e.entity_type='workflow_delegation'
                       AND e.entity_id::text='00000000-0000-4000-8000-0000beef0210') = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Screen 5 (Workflow Builder) — getWorkflowDefinitionDetail reads a
      // definition's groups (ordered by group_no) and their approvers.
      name: "wf-builder: definition detail reads groups (ordered) + approvers",
      setupSql: `INSERT INTO portal.workflow_definitions (code, name, is_active, updated_at)
                 VALUES ('abed_wf','Abed builder demo', FALSE, NOW());
                 INSERT INTO portal.workflow_groups (id, definition_code, group_no, name, quorum) VALUES
                   ('00000000-0000-4000-8000-0000abed0001'::uuid,'abed_wf',1,'First',1),
                   ('00000000-0000-4000-8000-0000abed0002'::uuid,'abed_wf',2,'Second',1);
                 INSERT INTO portal.workflow_group_approvers (group_id, approver_type, approver_level, sort_order) VALUES
                   ('00000000-0000-4000-8000-0000abed0001'::uuid,'access_level','L1',1),
                   ('00000000-0000-4000-8000-0000abed0001'::uuid,'access_level','L2',2),
                   ('00000000-0000-4000-8000-0000abed0002'::uuid,'access_level','L0',1)`,
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.workflow_groups WHERE definition_code='abed_wf') = 2
              AND (SELECT string_agg(name, ',' ORDER BY group_no)
                     FROM portal.workflow_groups WHERE definition_code='abed_wf') = 'First,Second'
              AND (SELECT COUNT(*) FROM portal.workflow_group_approvers a
                     JOIN portal.workflow_groups g ON g.id = a.group_id
                     WHERE g.definition_code='abed_wf') = 3
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Screen 5 — the edit gate: a definition with a pending instance counts as
      // "running" and must be refused for editing (edit only draft copies).
      name: "wf-builder: a definition with a pending instance is detected as running (edit gate)",
      setupSql: `INSERT INTO portal.workflow_definitions (code, name, is_active, updated_at)
                 VALUES ('abed_gate','Abed gate', FALSE, NOW());
                 INSERT INTO portal.workflow_instances
                   (id, workflow_code, resource_type, resource_id, current_step, status)
                 VALUES ('00000000-0000-4000-8000-0000abed0101'::uuid,'abed_gate','projects',
                         '00000000-0000-4000-8000-0000abed0102'::uuid, 1, 'pending')`,
      sql: `SELECT ((SELECT COUNT(*) FROM portal.workflow_instances
                     WHERE workflow_code='abed_gate' AND status='pending') = 1)::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Screen 5 — the atomic structure save replaces groups by DELETE-then-
      // reinsert; it relies on approvers cascading from workflow_groups.
      name: "wf-builder: deleting a group cascades its approvers (structure replace relies on this)",
      setupSql: `INSERT INTO portal.workflow_definitions (code, name, is_active, updated_at)
                 VALUES ('abed_casc','Abed cascade', FALSE, NOW());
                 INSERT INTO portal.workflow_groups (id, definition_code, group_no, name, quorum)
                 VALUES ('00000000-0000-4000-8000-0000abed0201'::uuid,'abed_casc',1,'G',1);
                 INSERT INTO portal.workflow_group_approvers (group_id, approver_type, approver_level, sort_order)
                 VALUES ('00000000-0000-4000-8000-0000abed0201'::uuid,'access_level','L1',1);
                 DELETE FROM portal.workflow_groups WHERE definition_code='abed_casc'`,
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.workflow_groups WHERE definition_code='abed_casc') = 0
              AND (SELECT COUNT(*) FROM portal.workflow_group_approvers
                     WHERE group_id='00000000-0000-4000-8000-0000abed0201') = 0
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Project Hub — the read model joins ee.projects → families (client name) and
      // → users (CRM TL), and each detail section (phases, billing, WIOs incl. the
      // days-remaining clock) hangs off project_id. Self-contained.
      name: "project-hub: list joins family + TL, detail reads phases/billing/wio",
      setupSql: `INSERT INTO public.families (id, primary_contact)
                 VALUES ('00000000-0000-4000-8000-0000ace00001'::uuid,'Test Family Ace');
                 INSERT INTO ee.projects
                   (id, project_code, family_id, site_address, rag_status, crmtl_id, current_phase, is_active)
                 VALUES ('00000000-0000-4000-8000-0000ace00002'::uuid,'ED/99-99/001',
                         '00000000-0000-4000-8000-0000ace00001'::uuid,'1 Test Rd','red',
                         '00000000-0000-4000-8000-000000000001'::uuid,'discovery',TRUE);
                 INSERT INTO ee.activity_phases (project_id, phase, completion_pct, status)
                 VALUES ('00000000-0000-4000-8000-0000ace00002'::uuid,'discovery',50,'in_progress');
                 INSERT INTO ee.billing_milestones (project_id, milestone_name, amount)
                 VALUES ('00000000-0000-4000-8000-0000ace00002'::uuid,'Signing',1000000);
                 INSERT INTO ee.wio (wio_number, project_id, department_code, target_pio_date)
                 VALUES ('WIO/99-99/001/ARCH','00000000-0000-4000-8000-0000ace00002'::uuid,'ARCH', CURRENT_DATE + 10)`,
      sql: `SELECT (
              (SELECT f.primary_contact FROM ee.projects p JOIN public.families f ON f.id = p.family_id
                 WHERE p.id='00000000-0000-4000-8000-0000ace00002') = 'Test Family Ace'
              AND (SELECT u.full_name IS NOT NULL FROM ee.projects p JOIN public.users u ON u.id = p.crmtl_id
                     WHERE p.id='00000000-0000-4000-8000-0000ace00002')
              AND (SELECT rag_status::text FROM ee.projects WHERE id='00000000-0000-4000-8000-0000ace00002') = 'red'
              AND (SELECT COUNT(*) FROM ee.activity_phases WHERE project_id='00000000-0000-4000-8000-0000ace00002') = 1
              AND (SELECT COUNT(*) FROM ee.billing_milestones WHERE project_id='00000000-0000-4000-8000-0000ace00002') = 1
              AND (SELECT (target_pio_date - CURRENT_DATE)::int FROM ee.wio
                     WHERE project_id='00000000-0000-4000-8000-0000ace00002') = 10
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // WIO/GFC approval on the engine (028) — the definition seeds the three
      // internal sign-off groups (Vishakha → Yoginder → Khushpreet), active, one
      // approver each, ready for startWorkflow('wio_approval','wio', id).
      name: "wf-wio: wio_approval seeds the active 3-group GFC sign-off chain",
      sql: `SELECT (
              (SELECT COUNT(*) FROM portal.workflow_definitions
                 WHERE code='wio_approval' AND is_active AND resource_type='wio') = 1
              AND (SELECT COUNT(*) FROM portal.workflow_groups WHERE definition_code='wio_approval') = 3
              AND (SELECT COUNT(*) FROM portal.workflow_group_approvers a
                     JOIN portal.workflow_groups g ON g.id = a.group_id
                     WHERE g.definition_code='wio_approval') = 3
              AND (SELECT string_agg(name, ' -> ' ORDER BY group_no)
                     FROM portal.workflow_groups WHERE definition_code='wio_approval')
                  = 'WIO / GFC Head sign-off -> Design sign-off -> Production Head sign-off'
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // Design Room (S5) — the 14-stage Drawing Ladder seeds for ED/26-27/901,
      // and the counts that drive the progress metrics (7 complete = 50%, 2
      // awaiting approval, current level GFC at the first non-complete stage).
      name: "design-room: 14-stage Drawing Ladder seeds with derived progress",
      sql: `SELECT (
              (SELECT COUNT(*) FROM ee.design_stages
                 WHERE project_id='00000000-0000-4000-8000-00000000a001') = 14
              AND (SELECT COUNT(*) FROM ee.design_stages
                     WHERE project_id='00000000-0000-4000-8000-00000000a001' AND status='complete') = 7
              AND (SELECT COUNT(*) FROM ee.design_stages
                     WHERE project_id='00000000-0000-4000-8000-00000000a001' AND status='pending_approval') = 2
              AND (SELECT drawing_level FROM ee.design_stages
                     WHERE project_id='00000000-0000-4000-8000-00000000a001' AND stage_no=8) = 'GFC'
              AND (SELECT stage_name FROM ee.design_stages
                     WHERE project_id='00000000-0000-4000-8000-00000000a001'
                     ORDER BY stage_no LIMIT 1) LIKE 'Conceptualisation%'
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // VisionCAM (S3) — the photo log seeds for ED/26-27/903 (4 captures, 3 QC
      // pass) and a photo-gated billing milestone is blocked awaiting a photo
      // (trigger_type='visioncam', not invoice_raised) — the Gate-1 surface.
      // S6 · EH (Velocity Gate 5). Three centres seed, each with a target, and
      // the gate threshold is a per-centre COLUMN, not a constant in code —
      // the business retunes a centre by UPDATE (ADR-EP-01).
      name: "eh: three Experience Centres seed with per-centre discount thresholds",
      sql: `SELECT (
              (SELECT COUNT(*) FROM eh.experience_centres) = 3
              AND (SELECT COUNT(*) FROM eh.experience_centres WHERE target_monthly > 0) = 3
              AND (SELECT discount_threshold_pct FROM eh.experience_centres
                     WHERE code='gurugram_hq') = 10.00
              AND (SELECT discount_threshold_pct FROM eh.experience_centres
                     WHERE code='mumbai_lower_parel') = 15.00
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // The gate's own shape: unapproved discounts at/above threshold are the
      // pending queue, and two of them are LOGGED BREACHES — communicated to
      // the family before sign-off. The breach is recorded, not prevented
      // (ADR-HS-01): a CHECK forcing FALSE would make it unrecordable.
      name: "eh: discount gate — pending queue + breaches recorded, not suppressed",
      sql: `SELECT (
              (SELECT COUNT(*) FROM eh.sales s
                 JOIN eh.experience_centres ec ON ec.id = s.ec_id
                WHERE s.discount_approved_at IS NULL
                  AND s.discount_pct >= ec.discount_threshold_pct
                  AND s.discount_pct > 0) = 3
              AND (SELECT COUNT(*) FROM eh.sales
                     WHERE discount_communicated_before_approval) = 2
              AND (SELECT COUNT(*) FROM eh.sales
                     WHERE discount_communicated_before_approval
                       AND discount_approved_at IS NULL) = 2
              AND (SELECT COUNT(*) FROM eh.sales
                     WHERE discount_approved_at IS NOT NULL) = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // A discount below its centre's threshold never enters the queue at all.
      name: "eh: a discount below the centre threshold needs no sign-off",
      sql: `SELECT (
              (SELECT COUNT(*) FROM eh.sales s
                 JOIN eh.experience_centres ec ON ec.id = s.ec_id
                WHERE s.discount_pct > 0
                  AND s.discount_pct < ec.discount_threshold_pct) = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      // The Country Head is L2 and would read ZERO rows under db/001's
      // L0/L1-only policy — on their own screen. db/029 adds ownership-scoped
      // access, the same shape as families_project_team.
      // A gate nobody can pass is not a gate. The Country Head is the actor
      // §28 names, so L2 must hold approve + financial_access on eh_sales —
      // while pio.approve stays denied at L2, which is a different rule (§26).
      name: "eh: the Country Head (L2) can actually work the gate",
      sql: `SELECT (
              (SELECT allowed FROM public.permissions
                WHERE access_level='L2' AND resource_type='eh_sales' AND action_code='approve')
              AND (SELECT allowed FROM public.permissions
                     WHERE access_level='L2' AND resource_type='eh_sales' AND action_code='financial_access')
              AND NOT (SELECT allowed FROM public.permissions
                         WHERE access_level='L2' AND resource_type='pio' AND action_code='approve')
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "eh: RLS grants the Country Head their own centre (db/029)",
      sql: `SELECT (
              (SELECT COUNT(*) FROM pg_policies
                WHERE schemaname='eh' AND tablename='sales'
                  AND policyname='eh_sales_country_head') = 1
              AND (SELECT COUNT(*) FROM eh.experience_centres
                     WHERE country_head_id='00000000-0000-4000-8000-000000000006') = 1
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
    {
      name: "visioncam: photo log + photo-gated (blocked) billing milestone seed",
      sql: `SELECT (
              (SELECT COUNT(*) FROM ee.visioncam_photos
                 WHERE project_id='00000000-0000-4000-8000-00000000a003') = 4
              AND (SELECT COUNT(*) FROM ee.visioncam_photos
                     WHERE project_id='00000000-0000-4000-8000-00000000a003' AND qc_status='pass') = 3
              AND (SELECT COUNT(*) FROM ee.billing_milestones
                     WHERE project_id='00000000-0000-4000-8000-00000000a003'
                       AND trigger_type='visioncam' AND NOT invoice_raised) = 1
              AND (SELECT amount FROM ee.billing_milestones
                     WHERE project_id='00000000-0000-4000-8000-00000000a003'
                       AND trigger_type='visioncam') = 240000
            )::TEXT AS v`,
      ok: (v) => v === "true",
    },
  ];

  // RLS bypass note: PGlite runs as a superuser-ish single role, so the RLS
  // check forces the policy path with row_security and a non-owner role.
  await db.exec(`
    CREATE ROLE app_user NOLOGIN;
    GRANT USAGE ON SCHEMA ee, eh, factory, proc, portal, audit TO app_user;
    GRANT SELECT ON ALL TABLES IN SCHEMA ee, eh, public TO app_user;
  `);

  for (const check of checks) {
    try {
      if (check.setupSql) await db.exec(check.setupSql);
      if (check.asRestrictedRole) await db.exec("SET ROLE app_user");
      const res = await db.query(check.sql);
      if (check.asRestrictedRole) await db.exec("RESET ROLE");
      if (check.expectError) {
        console.error(`FAIL    ${check.name} — expected an error but the statement succeeded`);
        failed = true;
        continue;
      }
      const v = res.rows[0]?.v;
      if (check.ok(String(v))) {
        console.log(`PASS    ${check.name}`);
      } else {
        console.error(`FAIL    ${check.name} — got: ${v}`);
        failed = true;
      }
    } catch (err) {
      if (check.asRestrictedRole) await db.exec("RESET ROLE").catch(() => {});
      if (check.expectError) {
        console.log(`PASS    ${check.name}`);
      } else {
        console.error(`FAIL    ${check.name} — ${err.message}`);
        failed = true;
      }
    }
  }

  const tables = await db.query(`
    SELECT COUNT(*)::INT AS n FROM information_schema.tables
    WHERE table_schema IN ('public','ee','eh','factory','proc','portal','audit')
      AND table_type = 'BASE TABLE'
  `);
  console.log(`INFO    base tables created: ${tables.rows[0].n}`);
}

process.exit(failed ? 1 : 0);
